// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
using DKNet.EfCore.DtoEntities.Share;
using System.ComponentModel.DataAnnotations;

namespace EfCore.DtoGenerator.Tests.Features.StaticData.ChannelDatas;

/// <summary>
/// Generated DTO for entity ChannelData.
/// </summary>
public partial record ChannelDto
{
    /// <summary>
    /// Gets or sets the Country.
    /// </summary>
    [MaxLength(3)]
    public required string Country { get; init; }
    /// <summary>
    /// Gets or sets the Currency.
    /// </summary>
    [MaxLength(4)]
    public required string Currency { get; init; }
    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    [MaxLength(50)]
    public required string Name { get; init; }
    /// <summary>
    /// Gets or sets the Code.
    /// </summary>
    [MaxLength(10)]
    public ChannelCodes Code { get; init; }
    /// <summary>
    /// Gets or sets the MaxAmount.
    /// </summary>
    public decimal? MaxAmount { get; init; }
    /// <summary>
    /// Gets or sets the MinAmount.
    /// </summary>
    public decimal MinAmount { get; init; }
    /// <summary>
    /// Gets or sets the Settlement.
    /// </summary>
    public required string Settlement { get; init; }
    /// <summary>
    /// Gets or sets the CreatedBy.
    /// </summary>
    [MaxLength(500)]
    public required string CreatedBy { get; init; }
    /// <summary>
    /// Gets or sets the CreatedOn.
    /// </summary>
    public DateTimeOffset CreatedOn { get; init; }
    /// <summary>
    /// Gets or sets the LastModifiedBy.
    /// </summary>
    public required string LastModifiedBy { get; init; }
    /// <summary>
    /// Gets or sets the LastModifiedOn.
    /// </summary>
    public DateTimeOffset LastModifiedOn { get; init; }
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    public int Id { get; init; }
}
