// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
using DKNet.EfCore.DtoEntities;
using System.Collections.Generic;

namespace EfCore.DtoGenerator.Tests.Features;

/// <summary>
/// Generated DTO for entity Customer.
/// </summary>
public partial record CustomerDto
{
    /// <summary>
    /// Gets or sets the CustomerId.
    /// </summary>
    public int CustomerId { get; init; }
    /// <summary>
    /// Gets or sets the Email.
    /// </summary>
    public string? Email { get; init; }
    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    public required string Name { get; init; }
    /// <summary>
    /// Gets or sets the Orders.
    /// </summary>
    public ICollection<Order> Orders { get; init; } = [];
    /// <summary>
    /// Gets or sets the PrimaryAddress.
    /// </summary>
    public Address? PrimaryAddress { get; init; }
    /// <summary>
    /// Gets or sets the CreatedUtc.
    /// </summary>
    public DateTime CreatedUtc { get; init; }
    /// <summary>
    /// Gets or sets the UpdatedUtc.
    /// </summary>
    public DateTime? UpdatedUtc { get; init; }
}
