// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace EfCore.DtoGenerator.Tests.Features;

/// <summary>
/// Generated DTO for entity Customer.
/// </summary>
public partial record CustomerWithExcludeDto
{
    /// <summary>
    /// Gets or sets the CustomerId.
    /// </summary>
    public int CustomerId { get; init; }
    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    public required string Name { get; init; }
    /// <summary>
    /// Gets or sets the CreatedUtc.
    /// </summary>
    public DateTime CreatedUtc { get; init; }
    /// <summary>
    /// Gets or sets the UpdatedUtc.
    /// </summary>
    public DateTime? UpdatedUtc { get; init; }
}
