// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace EfCore.DtoGenerator.Tests.Features;

/// <summary>
/// Generated DTO for entity GlobalExclusionTestEntity.
/// </summary>
public partial record IncludeOverridesGlobalExclusionTestDto
{
    /// <summary>
    /// Gets or sets the CreatedAt.
    /// </summary>
    public DateTime CreatedAt { get; init; }
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    public Guid Id { get; init; }
    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    public required string Name { get; init; }
}
