// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace EfCore.DtoGenerator.Tests.Features;

/// <summary>
/// Generated DTO for entity Person.
/// </summary>
public partial record PersonNameDto
{
    /// <summary>
    /// Gets or sets the FirstName.
    /// </summary>
    public required string FirstName { get; init; }
    /// <summary>
    /// Gets or sets the LastName.
    /// </summary>
    public required string LastName { get; init; }
}
