<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\NugetLogo.png" Pack="true" PackagePath="\"/>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DKNet.AspCore.Idempotency\DKNet.AspCore.Idempotency.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DKNet.AspCore.Idempotency.MsSqlStore"/>
        <InternalsVisibleTo Include="DKNet.AspCore.Idempotency.NpgsqlStore"/>
        <InternalsVisibleTo Include="AspCore.Idempotency.MsSqlStore.Tests"/>
        <InternalsVisibleTo Include="AspCore.Idempotency.NpgsqlStore.Tests"/>
    </ItemGroup>

</Project>
