// <auto-generated/>
// This file is automatically included in projects that reference DKNet.EfCore.DtoGenerator.

using System;

namespace DKNet.EfCore.DtoGenerator;

/// <summary>
/// Identifies which entity lifecycle operation(s) a <see cref="GenerateEventAttribute"/> declaration covers.
/// </summary>
/// <remarks>
/// Kept local to this package (rather than referencing <c>DKNet.EfCore.Abstractions.Events.EventOperations</c>)
/// so that <c>DKNet.EfCore.DtoGenerator</c> stays dependency-free for consumers who only use the DTO generator.
/// The event generator maps this enum onto <c>EventOperations</c> when emitting the assembly-level registration.
/// </remarks>
[Flags]
internal enum EventKinds
{
    /// <summary>
    /// The entity was added and the save succeeded.
    /// </summary>
    Created = 1,

    /// <summary>
    /// The entity was modified and the save succeeded.
    /// </summary>
    Updated = 2,

    /// <summary>
    /// The entity was removed and the save succeeded.
    /// </summary>
    Deleted = 4,
}
