// <auto-generated/> Public source generator implementation emitting [GenerateEvent]-declared domain events.
// Consumers reference this project/package as an Analyzer. Keep logic cohesive here.

using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace DKNet.EfCore.DtoGenerator;

#nullable enable

/// <summary>
/// Incremental source generator for <c>[GenerateEvent]</c> declarations. For each declaration on an entity,
/// emits a strongly-typed event record mirroring the entity's properties (reusing <see cref="DtoGenerator"/>'s
/// inclusion/exclusion/related-entity rules) and, when the runtime contract is resolvable in the compilation,
/// registers it via an assembly-level <c>DKNet.EfCore.Abstractions.Events.GeneratedEventAttribute</c> so
/// <c>DKNet.EfCore.Events</c> raises it automatically after a successful save.
/// </summary>
[ExcludeFromCodeCoverage]
[Generator]
[SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1041:This compiler extension should not be implemented in an assembly with target framework", Justification = "Targeting .NET 9+ only")]
public sealed class EventGenerator : IIncrementalGenerator
{
    #region Constants

    private const string AttributeShortName = "GenerateEvent";
    private const string AttributeFullName = "GenerateEventAttribute";
    private const string NameSuffixParameterName = "NameSuffix";
    private const string KindsParameterName = "Kinds";
    private const string PropertiesParameterName = "Properties";
    private const string ExcludeParameterName = "Exclude";
    private const string IncludeParameterName = "Include";
    private const string IgnoreComplexTypeParameterName = "IgnoreComplexType";
    private const string DiagnosticCategory = "DKNet.EfCore.DtoGenerator";

    private const int KindCreated = 1;
    private const int KindUpdated = 2;
    private const int KindDeleted = 4;

    private const string GeneratedEventAttributeMetadataName = "DKNet.EfCore.Abstractions.Events.GeneratedEventAttribute";
    private const string EventOperationsMetadataName = "DKNet.EfCore.Abstractions.Events.EventOperations";

    #endregion

    #region Initialization

    /// <summary>
    /// Initializes the incremental generator. Registers the syntax provider and source output.
    /// </summary>
    /// <param name="context">The generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var declarations = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) => ExtractDeclarations(ctx))
            .SelectMany(static (list, _) => list);

        var compilation = context.CompilationProvider.Combine(declarations.Collect());
        var compilationWithOptions = compilation.Combine(context.AnalyzerConfigOptionsProvider);

        context.RegisterSourceOutput(compilationWithOptions, static (spc, pair) =>
        {
            var ((compilation, targets), optionsProvider) = pair;

            var globalExclusions = DtoGenerator.ExtractGlobalExclusionsFromConfig(optionsProvider);
            var projectWideIgnoreComplexType = DtoGenerator.ExtractProjectWideIgnoreComplexTypeFromConfig(optionsProvider);

            var generatedEventAttributeSymbol = compilation.GetTypeByMetadataName(GeneratedEventAttributeMetadataName);
            var eventOperationsSymbol = compilation.GetTypeByMetadataName(EventOperationsMetadataName);
            var canEmitRegistration = generatedEventAttributeSymbol is not null && eventOperationsSymbol is not null;

            foreach (var group in targets.GroupBy(t => (ISymbol)t.EntitySymbol, SymbolEqualityComparer.Default))
            {
                GenerateForEntity(spc, compilation, (INamedTypeSymbol)group.Key!, group.ToList(), globalExclusions,
                    projectWideIgnoreComplexType, canEmitRegistration);
            }
        });
    }

    #endregion

    #region Attribute Detection & Parsing

    /// <summary>
    /// Extracts every <c>[GenerateEvent]</c> declaration from a type declaration's attributes.
    /// </summary>
    /// <param name="ctx">The generator syntax context.</param>
    /// <returns>A list of declarations found on this node (empty when none).</returns>
    private static List<EventDeclaration> ExtractDeclarations(GeneratorSyntaxContext ctx)
    {
        var results = new List<EventDeclaration>();

        if (ctx.Node is not TypeDeclarationSyntax typeDeclaration)
            return results;

        var entitySymbol = ctx.SemanticModel.GetDeclaredSymbol(typeDeclaration) as INamedTypeSymbol;
        if (entitySymbol is null)
            return results;

        foreach (var attributeList in typeDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (!IsGenerateEventAttribute(attribute))
                    continue;

                results.Add(new EventDeclaration
                {
                    EntitySymbol = entitySymbol,
                    NameSuffix = ExtractNameSuffixFromAttribute(ctx, attribute),
                    Kinds = ExtractKindsFromAttribute(ctx, attribute),
                    Properties = ExtractNamedArrayArgument(ctx, attribute, PropertiesParameterName),
                    IncludedProperties = ExtractNamedArrayArgument(ctx, attribute, IncludeParameterName),
                    ExcludedProperties = ExtractNamedArrayArgument(ctx, attribute, ExcludeParameterName),
                    IgnoreComplexType = ExtractIgnoreComplexTypeFromAttribute(ctx, attribute),
                    Location = attribute.GetLocation(),
                });
            }
        }

        return results;
    }

    /// <summary>
    /// Checks if the attribute is a [GenerateEvent] attribute.
    /// </summary>
    private static bool IsGenerateEventAttribute(AttributeSyntax attribute)
    {
        var shortName = attribute.Name switch
        {
            IdentifierNameSyntax ins => ins.Identifier.Text,
            QualifiedNameSyntax qns => qns.Right.Identifier.Text,
            _ => null
        };

        return shortName is AttributeShortName or AttributeFullName;
    }

    private static string? ExtractNameSuffixFromAttribute(GeneratorSyntaxContext ctx, AttributeSyntax attribute)
    {
        foreach (var arg in attribute.ArgumentList?.Arguments ?? default)
        {
            if (arg.NameEquals?.Name.Identifier.Text != NameSuffixParameterName)
                continue;

            var constantValue = ctx.SemanticModel.GetConstantValue(arg.Expression);
            if (constantValue.HasValue && constantValue.Value is string suffix)
                return suffix;
        }

        return null;
    }

    /// <summary>
    /// Extracts the <c>Kinds</c> flags value from the attribute as a bitmask of <see cref="KindCreated"/>,
    /// <see cref="KindUpdated"/> and <see cref="KindDeleted"/>.
    /// </summary>
    private static int ExtractKindsFromAttribute(GeneratorSyntaxContext ctx, AttributeSyntax attribute)
    {
        foreach (var arg in attribute.ArgumentList?.Arguments ?? default)
        {
            if (arg.NameEquals?.Name.Identifier.Text != KindsParameterName)
                continue;

            var constantValue = ctx.SemanticModel.GetConstantValue(arg.Expression);
            if (constantValue.HasValue && constantValue.Value is not null)
                return Convert.ToInt32(constantValue.Value);
        }

        return 0;
    }

    private static HashSet<string> ExtractNamedArrayArgument(GeneratorSyntaxContext ctx, AttributeSyntax attribute, string parameterName)
    {
        foreach (var arg in attribute.ArgumentList?.Arguments ?? default)
        {
            if (arg.NameEquals?.Name.Identifier.Text == parameterName)
                return DtoGenerator.ExtractExcludedPropertiesFromExpression(ctx, arg.Expression);
        }

        return new HashSet<string>();
    }

    private static bool? ExtractIgnoreComplexTypeFromAttribute(GeneratorSyntaxContext ctx, AttributeSyntax attribute)
    {
        foreach (var arg in attribute.ArgumentList?.Arguments ?? default)
        {
            if (arg.NameEquals?.Name.Identifier.Text != IgnoreComplexTypeParameterName)
                continue;

            var constantValue = ctx.SemanticModel.GetConstantValue(arg.Expression);
            if (constantValue.HasValue && constantValue.Value is bool boolValue)
                return boolValue;
        }

        return null;
    }

    #endregion

    #region Event Source Generation

    /// <summary>
    /// Resolves names, validates, and emits generated sources for every declaration on one entity.
    /// </summary>
    private static void GenerateForEntity(
        SourceProductionContext context,
        Compilation compilation,
        INamedTypeSymbol entitySymbol,
        List<EventDeclaration> declarations,
        HashSet<string> globalExclusions,
        bool? projectWideIgnoreComplexType,
        bool canEmitRegistration)
    {
        var entityProperties = DtoGenerator.GetEntityProperties(entitySymbol);
        var named = declarations
            .Select(d => (Decl: d, Name: ResolveEventName(context, entitySymbol, d)))
            .ToList();

        // Duplicate-name detection: skip every declaration that shares a resolved name with another.
        var duplicateNames = new HashSet<string>(
            named.Where(n => n.Name is not null)
                .GroupBy(n => n.Name, StringComparer.Ordinal)
                .Where(g => g.Count() > 1)
                .Select(g => g.Key!),
            StringComparer.Ordinal);

        foreach (var (decl, name) in named)
        {
            if (name is null)
                continue;

            if (duplicateNames.Contains(name))
            {
                ReportDiagnostic(context, "DKDTOEVT002", "Duplicate generated event name",
                    "Entity {0}: more than one [GenerateEvent] declaration resolves to the event name '{1}'. Give each a distinct NameSuffix.",
                    DiagnosticSeverity.Error, decl.Location, entitySymbol.Name, name);
                continue;
            }

            if (!ValidateNarrowingProperties(context, entitySymbol, decl, entityProperties))
                continue;

            if (decl.Properties.Count > 0 && (decl.Kinds & KindUpdated) == 0)
            {
                ReportDiagnostic(context, "DKDTOEVT004", "Update narrowing ignored",
                    "Entity {0}, event {1}: Properties narrowing is ignored because Kinds has no Updated flag.",
                    DiagnosticSeverity.Warning, decl.Location, entitySymbol.Name, name);
            }

            GenerateEventSource(context, compilation, entitySymbol, decl, name, entityProperties,
                globalExclusions, projectWideIgnoreComplexType, canEmitRegistration);
        }
    }

    /// <summary>
    /// Resolves the generated event name for a declaration, reporting a build error for the ambiguous
    /// no-suffix multi-kind case (Q1) and returning <see langword="null"/> for anything unresolvable.
    /// </summary>
    private static string? ResolveEventName(SourceProductionContext context, INamedTypeSymbol entitySymbol, EventDeclaration decl)
    {
        if (decl.Kinds == 0)
        {
            ReportDiagnostic(context, "DKDTOEVT005", "No operations declared",
                "Entity {0}: a [GenerateEvent] declaration with no Kinds set generates nothing.",
                DiagnosticSeverity.Warning, decl.Location, entitySymbol.Name);
            return null;
        }

        if (!string.IsNullOrWhiteSpace(decl.NameSuffix))
            return $"{entitySymbol.Name}{decl.NameSuffix}Event";

        var kindName = decl.Kinds switch
        {
            KindCreated => "Created",
            KindUpdated => "Updated",
            KindDeleted => "Deleted",
            _ => null,
        };

        if (kindName is null)
        {
            ReportDiagnostic(context, "DKDTOEVT003", "Ambiguous generated event name",
                "Entity {0}: a [GenerateEvent] declaration covering more than one Kind requires an explicit NameSuffix.",
                DiagnosticSeverity.Error, decl.Location, entitySymbol.Name);
            return null;
        }

        return $"{entitySymbol.Name}{kindName}Event";
    }

    /// <summary>
    /// Validates the update-narrowing <c>Properties</c> list names direct, existing properties of the entity.
    /// </summary>
    private static bool ValidateNarrowingProperties(
        SourceProductionContext context,
        INamedTypeSymbol entitySymbol,
        EventDeclaration decl,
        List<IPropertySymbol> entityProperties)
    {
        var valid = true;

        foreach (var propertyName in decl.Properties)
        {
            if (propertyName.Contains('.'))
            {
                ReportDiagnostic(context, "DKDTOEVT001", "Invalid narrowing property",
                    "Entity {0}: narrowing property '{1}' is a nested path, which is not supported.",
                    DiagnosticSeverity.Error, decl.Location, entitySymbol.Name, propertyName);
                valid = false;
                continue;
            }

            if (entityProperties.All(p => p.Name != propertyName))
            {
                ReportDiagnostic(context, "DKDTOEVT001", "Invalid narrowing property",
                    "Entity {0}: narrowing property '{1}' is not a property of the entity.",
                    DiagnosticSeverity.Error, decl.Location, entitySymbol.Name, propertyName);
                valid = false;
            }
        }

        return valid;
    }

    private static void GenerateEventSource(
        SourceProductionContext context,
        Compilation compilation,
        INamedTypeSymbol entitySymbol,
        EventDeclaration decl,
        string eventName,
        List<IPropertySymbol> entityProperties,
        HashSet<string> globalExclusions,
        bool? projectWideIgnoreComplexType,
        bool canEmitRegistration)
    {
        var effectiveIgnoreComplexType = decl.IgnoreComplexType ?? projectWideIgnoreComplexType ?? true;
        var properties = DtoGenerator.FilterIncludedProperties(entityProperties, decl.ExcludedProperties,
            decl.IncludedProperties, globalExclusions, effectiveIgnoreComplexType, compilation);

        var namespaceName = entitySymbol.ContainingNamespace is { IsGlobalNamespace: false }
            ? entitySymbol.ContainingNamespace.ToDisplayString()
            : null;
        var requiredNamespaces = DtoGenerator.CollectRequiredNamespaces(properties, namespaceName);
        var typeFormat = DtoGenerator.CreateTypeDisplayFormat();
        var entityDisplayName = entitySymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

        string? registrationLine = null;
        if (canEmitRegistration)
        {
            var entityTypeArg = entitySymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var eventTypeArg = namespaceName is null ? $"global::{eventName}" : $"global::{namespaceName}.{eventName}";
            var operationsArg = FormatOperations(decl.Kinds);
            var propertiesArg = string.Join(", ", decl.Properties.Select(p => $"\"{p.Replace("\"", "\\\"")}\""));
            var argsTail = propertiesArg.Length > 0 ? $", {propertiesArg}" : string.Empty;

            registrationLine =
                $"[assembly: {GeneratedEventAttributeMetadataName}(typeof({entityTypeArg}), typeof({eventTypeArg}), {operationsArg}{argsTail})]";
        }

        var sourceCode = BuildEventSourceCode(namespaceName, eventName, entityDisplayName, properties,
            requiredNamespaces, typeFormat, registrationLine);

        context.AddSource($"{eventName}.g.cs", sourceCode);
    }

    private static string FormatOperations(int kinds)
    {
        var parts = new List<string>();
        if ((kinds & KindCreated) != 0) parts.Add($"{EventOperationsMetadataName}.Created");
        if ((kinds & KindUpdated) != 0) parts.Add($"{EventOperationsMetadataName}.Updated");
        if ((kinds & KindDeleted) != 0) parts.Add($"{EventOperationsMetadataName}.Deleted");
        return string.Join(" | ", parts);
    }

    private static string BuildEventSourceCode(
        string? namespaceName,
        string eventName,
        string entityDisplayName,
        List<IPropertySymbol> properties,
        HashSet<string> requiredNamespaces,
        SymbolDisplayFormat typeFormat,
        string? registrationLine)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator (event generator)");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        foreach (var namespaceEntry in requiredNamespaces.OrderBy(n => n, StringComparer.Ordinal))
            builder.Append("using ").Append(namespaceEntry).AppendLine(";");
        if (requiredNamespaces.Count > 0)
            builder.AppendLine();

        if (registrationLine is not null)
        {
            builder.AppendLine(registrationLine);
            builder.AppendLine();
        }

        if (namespaceName is not null)
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            builder.AppendLine();
        }

        builder.AppendLine("/// <summary>");
        builder.Append("/// Generated domain event for entity ").Append(entityDisplayName).AppendLine(".");
        builder.AppendLine("/// </summary>");
        builder.Append("public sealed record ").AppendLine(eventName);
        builder.AppendLine("{");

        foreach (var property in properties)
        {
            var typeName = DtoGenerator.GetPropertyTypeName(property, typeFormat);
            var isNonNullableString = DtoGenerator.IsNonNullableString(property);
            var isCollection = DtoGenerator.IsCollectionType(property);
            var isComplexReferenceType = DtoGenerator.IsComplexReferenceType(property);

            builder.AppendLine("    /// <summary>");
            builder.Append("    /// Gets or sets the ").Append(property.Name).AppendLine(".");
            builder.AppendLine("    /// </summary>");
            builder.Append("    public ");
            if (isNonNullableString)
                builder.Append("required ");
            builder.Append(typeName).Append(' ').Append(property.Name).Append(" { get; init; }");

            if (isCollection && property.NullableAnnotation != NullableAnnotation.Annotated)
                builder.Append(" = [];");
            else if (isComplexReferenceType)
                builder.Append(" = null!;");

            builder.AppendLine();
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>
    /// Reports a diagnostic at the given location using a lazily-built descriptor.
    /// </summary>
    private static void ReportDiagnostic(
        SourceProductionContext context,
        string id,
        string title,
        string messageFormat,
        DiagnosticSeverity severity,
        Location location,
        params object?[] args)
    {
        var descriptor = new DiagnosticDescriptor(id, title, messageFormat, DiagnosticCategory, severity,
            isEnabledByDefault: true);
        context.ReportDiagnostic(Diagnostic.Create(descriptor, location, args));
    }

    #endregion

    #region Data Models

    /// <summary>
    /// A single <c>[GenerateEvent]</c> declaration found on an entity's syntax.
    /// </summary>
    /// <remarks>
    /// ponytail: default record equality (INamedTypeSymbol reference equality) means the incremental
    /// pipeline recomputes on any edit rather than caching per-declaration; correctness is unaffected,
    /// only IDE re-generation latency. Upgrade to string-keyed Equals/GetHashCode (as DtoGenerator's
    /// Target does) if that latency ever matters.
    /// </remarks>
    private sealed record EventDeclaration
    {
        public INamedTypeSymbol EntitySymbol { get; set; } = null!;
        public string? NameSuffix { get; set; }
        public int Kinds { get; set; }
        public HashSet<string> Properties { get; set; } = new();
        public HashSet<string> IncludedProperties { get; set; } = new();
        public HashSet<string> ExcludedProperties { get; set; } = new();
        public bool? IgnoreComplexType { get; set; }
        public Location Location { get; set; } = Location.None;
    }

    #endregion
}
