// <auto-generated/>
// This file is automatically included in projects that reference DKNet.EfCore.DtoGenerator.

#nullable enable

using System;

namespace DKNet.EfCore.DtoGenerator;

/// <summary>
/// Attribute applied to an entity class to have the event generator emit a strongly-typed domain event
/// record mirroring the entity's properties, and register it so <c>DKNet.EfCore.Events</c> raises it
/// automatically after a successful save. Repeatable: apply more than once to declare several events
/// for the same entity.
/// </summary>
/// <remarks>
/// Example:
/// <code>
/// [GenerateEvent(Kinds = EventKinds.Created)]
/// [GenerateEvent(Kinds = EventKinds.Deleted, NameSuffix = "Removed")]
/// [GenerateEvent(Kinds = EventKinds.Updated, Properties = new[] { "Price" }, NameSuffix = "PriceChanged")]
/// public class Product { public Guid Id { get; set; } public decimal Price { get; set; } }
/// // Generates ProductCreatedEvent, ProductRemovedEvent, ProductPriceChangedEvent.
/// </code>
/// Naming: <see cref="NameSuffix"/> set → <c>{Entity}{NameSuffix}Event</c>. Unset and <see cref="Kinds"/>
/// covers exactly one operation → <c>{Entity}CreatedEvent</c> / <c>{Entity}UpdatedEvent</c> /
/// <c>{Entity}DeletedEvent</c>. Unset and <see cref="Kinds"/> covers more than one operation is a build
/// error — an explicit <see cref="NameSuffix"/> is required in that case.
/// <para>
/// <see cref="Include"/>, <see cref="Exclude"/> and <see cref="IgnoreComplexType"/> follow the same rules as
/// <see cref="GenerateDtoAttribute"/> (mutually exclusive Include/Exclude; effective IgnoreComplexType
/// resolves per-declaration → project-wide <c>DtoGeneratorIgnoreComplexType</c> → default <see langword="true"/>).
/// </para>
/// <para>
/// <see cref="Properties"/> narrows when an <see cref="EventKinds.Updated"/> event raises: non-empty means
/// raise only when at least one listed property changed; empty means any change qualifies. Ignored (with a
/// build warning) when <see cref="Kinds"/> has no <see cref="EventKinds.Updated"/> flag. Entries must be a
/// direct property of the entity — nested paths are a build error.
/// </para>
/// </remarks>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
internal sealed class GenerateEventAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the suffix used to name the generated event: <c>{Entity}{NameSuffix}Event</c>.
    /// Required when <see cref="Kinds"/> covers more than one operation.
    /// </summary>
    public string? NameSuffix { get; set; }

    /// <summary>
    /// Gets or sets the lifecycle operation(s) this declaration raises the generated event for.
    /// </summary>
    public EventKinds Kinds { get; set; }

    /// <summary>
    /// Gets or sets the narrowing property list for <see cref="EventKinds.Updated"/>. Non-empty raises
    /// only when at least one listed property changed; empty (default) raises on any change.
    /// This property is mutually exclusive with having no <see cref="EventKinds.Updated"/> flag set.
    /// </summary>
    public string[] Properties { get; set; } = [];

    /// <summary>
    /// Gets or sets the names of properties to include in the generated event.
    /// This property is mutually exclusive with <see cref="Exclude"/>.
    /// </summary>
    public string[] Include { get; set; } = [];

    /// <summary>
    /// Gets or sets the names of properties to exclude from the generated event.
    /// This property is mutually exclusive with <see cref="Include"/>.
    /// </summary>
    public string[] Exclude { get; set; } = [];

    /// <summary>
    /// Gets or sets a value indicating whether to automatically exclude complex navigation properties.
    /// When unset, falls through to the project-wide <c>DtoGeneratorIgnoreComplexType</c> MSBuild property,
    /// then to the built-in default of <see langword="true"/>.
    /// </summary>
    public bool IgnoreComplexType { get; set; }
}
