// <auto-generated/>
// This file is automatically included in projects that reference DKNet.EfCore.DtoGenerator.

namespace DKNet.EfCore.DtoGenerator;

/// <summary>
/// Attribute applied to an empty <c>partial record</c> (recommended) or class to instruct the DTO generator
/// to emit properties mirroring the public instance readable properties of the provided entity <see cref="System.Type"/>.
/// </summary>
/// <remarks>
/// Example:
/// <code>
/// public class Person { public Guid ID { get; set; } public string Name { get; set; } = string.Empty; }
/// [GenerateDto(typeof(Person))]
/// public partial record PersonDto; // Generated properties + mapping helpers.
///
/// // Exclude specific properties:
/// [GenerateDto(typeof(Person), Exclude = new[] { "ID", "CreatedAt" })]
/// public partial record PersonSummaryDto; // Generated without ID and CreatedAt properties.
///
/// // Include only specific properties:
/// [GenerateDto(typeof(Person), Include = new[] { "Name", "Email" })]
/// public partial record PersonNameDto; // Generated with only Name and Email properties.
///
/// // Ignore complex types (entity navigation properties):
/// [GenerateDto(typeof(Customer), IgnoreComplexType = true)]
/// public partial record CustomerSimpleDto; // Generated without navigation properties (e.g., Orders, Address).
///
/// // Combine IgnoreComplexType with Exclude:
/// [GenerateDto(typeof(Customer), IgnoreComplexType = true, Exclude = new[] { "Email" })]
/// public partial record CustomerBasicDto; // Generated without complex types and Email property.
/// </code>
/// Note: Include and Exclude are mutually exclusive. If Include is provided, only those properties will be generated.
/// When IgnoreComplexType is true, properties that link to other entities (classes without [Owned] attribute)
/// are automatically excluded, including both single entity properties and collection properties.
/// </remarks>
[System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
public sealed class GenerateDtoAttribute : System.Attribute
{
    /// <summary>
    /// Gets the entity type to generate a DTO for.
    /// </summary>
    public System.Type EntityType { get; }

    /// <summary>
    /// Gets or sets the names of properties to exclude from DTO generation.
    /// This property is mutually exclusive with <see cref="Include"/>.
    /// </summary>
    public string[] Exclude { get; set; } = [];

    /// <summary>
    /// Gets or sets the names of properties to include in DTO generation.
    /// When specified, only these properties will be generated.
    /// This property is mutually exclusive with <see cref="Exclude"/>.
    /// </summary>
    public string[] Include { get; set; } = [];

    /// <summary>
    /// Gets or sets a value indicating whether to automatically ignore complex types during DTO generation.
    /// When set to true, properties that link to other entities (classes without the Owned attribute)
    /// will be automatically excluded, including both single entity properties and collection properties.
    /// </summary>
    public bool IgnoreComplexType { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="GenerateDtoAttribute"/> class.
    /// </summary>
    /// <param name="entityType">The entity type to generate a DTO for.</param>
    public GenerateDtoAttribute(System.Type entityType) => EntityType = entityType;
}
