// <auto-generated/> Public configuration class for global DTO exclusions.
// This file is automatically included in projects that reference DKNet.EfCore.DtoGenerator.

namespace DKNet.EfCore.DtoGenerator;

/// <summary>
/// Provides information about global configuration for DTO generation.
/// Global exclusions are configured via MSBuild properties at compile-time.
/// </summary>
/// <remarks>
/// Global exclusions are applied universally to all DTOs unless overridden by
/// the Include parameter on the GenerateDto attribute. Local Exclude parameters are
/// combined with global exclusions.
/// <para>
/// To configure global exclusions, add the following to your .csproj file:
/// <code>
/// &lt;PropertyGroup&gt;
///   &lt;DtoGenerator_GlobalExclusions&gt;CreatedBy,UpdatedBy,CreatedAt,UpdatedAt&lt;/DtoGenerator_GlobalExclusions&gt;
/// &lt;/PropertyGroup&gt;
/// </code>
/// </para>
/// <para>
/// Examples:
/// <code>
/// // With global exclusions configured in .csproj:
/// // &lt;DtoGenerator_GlobalExclusions&gt;CreatedBy,UpdatedBy,CreatedAt,UpdatedAt&lt;/DtoGenerator_GlobalExclusions&gt;
/// 
/// // All DTOs will exclude these properties by default
/// [GenerateDto(typeof(Customer))]
/// public partial record CustomerDto; // Excludes CreatedBy, UpdatedBy, CreatedAt, UpdatedAt
/// 
/// // Local exclusions are combined with global exclusions
/// [GenerateDto(typeof(Customer), Exclude = ["InternalId"])]
/// public partial record CustomerSummaryDto; // Excludes all global + InternalId
/// 
/// // Include overrides global exclusions
/// [GenerateDto(typeof(Customer), Include = ["Id", "Name", "CreatedAt"])]
/// public partial record CustomerNameDto; // Only includes Id, Name, CreatedAt (ignores global exclusions)
/// </code>
/// </para>
/// </remarks>
public static class GlobalDtoConfiguration
{
    /// <summary>
    /// Documentation marker for global DTO configuration.
    /// Actual configuration is done via MSBuild properties (see class remarks).
    /// </summary>
    /// <remarks>
    /// To configure global exclusions at compile-time, add this to your .csproj:
    /// <code>
    /// &lt;PropertyGroup&gt;
    ///   &lt;DtoGenerator_GlobalExclusions&gt;PropertyName1,PropertyName2,PropertyName3&lt;/DtoGenerator_GlobalExclusions&gt;
    /// &lt;/PropertyGroup&gt;
    /// </code>
    /// </remarks>
    public const string ConfigurationDocumentation = "See class documentation for configuration instructions.";
}
