// <auto-generated/> Public source generator implementation validating [RaisesEvent] declarations.
// Consumers reference this project/package as an Analyzer. Keep logic cohesive here.

using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DKNet.EfCore.DtoGenerator;

#nullable enable

/// <summary>
/// Incremental generator that validates <c>[RaisesEvent]</c> declarations at build time. A raise rule carries
/// no generated code of its own — <c>DKNet.EfCore.Events</c> reads the attribute via reflection at runtime —
/// so this generator emits diagnostics only and never references <c>DKNet.EfCore.Events</c>.
/// </summary>
[ExcludeFromCodeCoverage]
[Generator]
[SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1041:This compiler extension should not be implemented in an assembly with target framework", Justification = "Targeting .NET 9+ only")]
public sealed class RaisesEventValidator : IIncrementalGenerator
{
    #region Constants

    private const string AttributeShortName = "RaisesEvent";
    private const string AttributeFullName = "RaisesEventAttribute";
    private const string GenerateDtoAttributeName = "GenerateDtoAttribute";
    private const string DiagnosticCategory = "DKNet.EfCore.DtoGenerator";

    // Mirrors DKNet.EfCore.Abstractions.Events.EventOperations.Updated without referencing that assembly.
    private const int OperationUpdated = 2;

    #endregion

    #region Initialization

    /// <summary>
    /// Initializes the incremental generator. Registers the syntax provider and diagnostic output.
    /// </summary>
    /// <param name="context">The generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var declarations = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) => ExtractDeclarations(ctx))
            .SelectMany(static (list, _) => list);

        context.RegisterSourceOutput(declarations.Collect(), static (spc, targets) =>
        {
            foreach (var declaration in targets)
                ValidateDeclaration(spc, declaration);
        });
    }

    #endregion

    #region Attribute Detection & Parsing

    /// <summary>
    /// Extracts every <c>[RaisesEvent]</c> declaration from a type declaration's attributes.
    /// </summary>
    private static List<RaisesEventDeclaration> ExtractDeclarations(GeneratorSyntaxContext ctx)
    {
        var results = new List<RaisesEventDeclaration>();

        if (ctx.Node is not TypeDeclarationSyntax typeDeclaration)
            return results;

        var entitySymbol = ctx.SemanticModel.GetDeclaredSymbol(typeDeclaration) as INamedTypeSymbol;
        if (entitySymbol is null)
            return results;

        foreach (var attributeList in typeDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (!IsRaisesEventAttribute(attribute))
                    continue;

                var declaration = ExtractDeclaration(ctx, entitySymbol, attribute);
                if (declaration is not null)
                    results.Add(declaration);
            }
        }

        return results;
    }

    /// <summary>
    /// Checks if the attribute is a [RaisesEvent] attribute.
    /// </summary>
    private static bool IsRaisesEventAttribute(AttributeSyntax attribute)
    {
        var shortName = attribute.Name switch
        {
            IdentifierNameSyntax ins => ins.Identifier.Text,
            QualifiedNameSyntax qns => qns.Right.Identifier.Text,
            _ => null
        };

        return shortName is AttributeShortName or AttributeFullName;
    }

    /// <summary>
    /// Extracts the event type, operations, and narrowing properties from a [RaisesEvent] declaration.
    /// </summary>
    private static RaisesEventDeclaration? ExtractDeclaration(
        GeneratorSyntaxContext ctx, INamedTypeSymbol entitySymbol, AttributeSyntax attribute)
    {
        var arguments = attribute.ArgumentList?.Arguments ?? default;
        if (arguments.Count < 2 || arguments[0].Expression is not TypeOfExpressionSyntax typeOfExpression)
            return null;

        var eventTypeSymbol = ctx.SemanticModel.GetTypeInfo(typeOfExpression.Type).Type as INamedTypeSymbol;

        var operationsValue = ctx.SemanticModel.GetConstantValue(arguments[1].Expression);
        var operations = operationsValue.HasValue && operationsValue.Value is not null
            ? Convert.ToInt32(operationsValue.Value)
            : 0;

        return new RaisesEventDeclaration
        {
            EntitySymbol = entitySymbol,
            EventTypeSymbol = eventTypeSymbol,
            Operations = operations,
            Properties = ExtractProperties(ctx, arguments),
            Location = attribute.GetLocation(),
        };
    }

    /// <summary>
    /// Extracts the narrowing property list from the trailing <c>params string[] properties</c> argument(s),
    /// supporting both an explicit array/collection expression and individually-passed params values.
    /// </summary>
    private static List<string> ExtractProperties(
        GeneratorSyntaxContext ctx, SeparatedSyntaxList<AttributeArgumentSyntax> arguments)
    {
        var trailing = arguments.Skip(2).Where(a => a.NameEquals is null).ToList();

        if (trailing.Count == 1 && trailing[0].Expression is ImplicitArrayCreationExpressionSyntax
            or ArrayCreationExpressionSyntax or CollectionExpressionSyntax)
        {
            return DtoGenerator.ExtractExcludedPropertiesFromExpression(ctx, trailing[0].Expression).ToList();
        }

        var result = new List<string>();
        foreach (var arg in trailing)
        {
            var constantValue = ctx.SemanticModel.GetConstantValue(arg.Expression);
            if (constantValue.HasValue && constantValue.Value is string propertyName)
                result.Add(propertyName);
        }

        return result;
    }

    #endregion

    #region Validation

    /// <summary>
    /// Validates a single [RaisesEvent] declaration: payload/entity match, narrowing property names, and
    /// narrowing-without-Updated.
    /// </summary>
    private static void ValidateDeclaration(SourceProductionContext context, RaisesEventDeclaration decl)
    {
        ValidatePayloadEntity(context, decl);

        if (decl.Properties.Count == 0)
            return;

        var entityProperties = DtoGenerator.GetEntityProperties(decl.EntitySymbol);

        foreach (var propertyName in decl.Properties)
        {
            if (propertyName.Contains('.'))
            {
                ReportDiagnostic(context, "DKRAISEVT001", "Invalid narrowing property", DiagnosticSeverity.Error,
                    decl.Location, "Entity {0}: narrowing property '{1}' is a nested path, which is not supported.",
                    decl.EntitySymbol.Name, propertyName);
                continue;
            }

            if (entityProperties.All(p => p.Name != propertyName))
            {
                ReportDiagnostic(context, "DKRAISEVT001", "Invalid narrowing property", DiagnosticSeverity.Error,
                    decl.Location, "Entity {0}: narrowing property '{1}' is not a property of the entity.",
                    decl.EntitySymbol.Name, propertyName);
            }
        }

        if ((decl.Operations & OperationUpdated) == 0)
        {
            ReportDiagnostic(context, "DKRAISEVT003", "Narrowing ignored", DiagnosticSeverity.Warning,
                decl.Location, "Entity {0}: narrowing is ignored because Operations has no Updated flag.",
                decl.EntitySymbol.Name);
        }
    }

    /// <summary>
    /// Validates that the named event type is a [GenerateDto] payload generated from the same entity that
    /// carries the [RaisesEvent] rule.
    /// </summary>
    private static void ValidatePayloadEntity(SourceProductionContext context, RaisesEventDeclaration decl)
    {
        if (decl.EventTypeSymbol is null)
            return;

        var generateDto = decl.EventTypeSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == GenerateDtoAttributeName);

        if (generateDto is null)
        {
            ReportDiagnostic(context, "DKRAISEVT002", "Payload entity mismatch", DiagnosticSeverity.Error,
                decl.Location,
                "Entity {0}: event type '{1}' does not carry [GenerateDto] and cannot be validated as a payload for this entity.",
                decl.EntitySymbol.Name, decl.EventTypeSymbol.Name);
            return;
        }

        if (generateDto.ConstructorArguments.Length == 0 ||
            generateDto.ConstructorArguments[0].Value is not ITypeSymbol payloadEntityType)
            return;

        if (!SymbolEqualityComparer.Default.Equals(payloadEntityType, decl.EntitySymbol))
        {
            ReportDiagnostic(context, "DKRAISEVT002", "Payload entity mismatch", DiagnosticSeverity.Error,
                decl.Location,
                "Entity {0}: event type '{1}' is generated from entity '{2}', not '{0}'.",
                decl.EntitySymbol.Name, decl.EventTypeSymbol.Name, payloadEntityType.Name);
        }
    }

    /// <summary>
    /// Reports a diagnostic at the given location using a lazily-built descriptor.
    /// </summary>
    private static void ReportDiagnostic(
        SourceProductionContext context,
        string id,
        string title,
        DiagnosticSeverity severity,
        Location location,
        string messageFormat,
        params object?[] args)
    {
        var descriptor = new DiagnosticDescriptor(id, title, messageFormat, DiagnosticCategory, severity,
            isEnabledByDefault: true);
        context.ReportDiagnostic(Diagnostic.Create(descriptor, location, args));
    }

    #endregion

    #region Data Models

    /// <summary>
    /// A single <c>[RaisesEvent]</c> declaration found on an entity's syntax.
    /// </summary>
    private sealed record RaisesEventDeclaration
    {
        public INamedTypeSymbol EntitySymbol { get; set; } = null!;
        public INamedTypeSymbol? EventTypeSymbol { get; set; }
        public int Operations { get; set; }
        public List<string> Properties { get; set; } = [];
        public Location Location { get; set; } = Location.None;
    }

    #endregion
}
