// <auto-generated/> Public source generator implementation validating [RaisesEvent] declarations.
// Consumers reference this project/package as an Analyzer. Keep logic cohesive here.

using System.Diagnostics.CodeAnalysis;
using DKNet.EfCore.Abstractions.Events;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DKNet.EfCore.DtoGenerator;

#nullable enable

/// <summary>
/// Incremental generator that validates <c>[RaisesEvent]</c> declarations at build time. The type-naming
/// form carries no generated code of its own — <c>DKNet.EfCore.Events</c> reads the attribute via reflection
/// at runtime. The convention forms generate a default-shape payload record (see <see cref="DtoGenerator"/>'s
/// <c>BuildRaisesEventRecordSource</c>, reused here) named by <see cref="EventNameComposer"/>, so this
/// generator never references <c>DKNet.EfCore.Events</c>.
/// </summary>
[ExcludeFromCodeCoverage]
[Generator]
[SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1041:This compiler extension should not be implemented in an assembly with target framework", Justification = "Targeting .NET 9+ only")]
public sealed class RaisesEventValidator : IIncrementalGenerator
{
    #region Constants

    private const string AttributeShortName = "RaisesEvent";
    private const string AttributeFullName = "RaisesEventAttribute";
    private const string GenerateDtoAttributeName = "GenerateDtoAttribute";
    private const string DiagnosticCategory = "DKNet.EfCore.DtoGenerator";

    // Mirrors DKNet.EfCore.Abstractions.Events.EventOperations.Updated without referencing that assembly.
    private const int OperationUpdated = 2;

    #endregion

    #region Initialization

    /// <summary>
    /// Initializes the incremental generator. Registers the syntax provider and diagnostic/source output.
    /// </summary>
    /// <param name="context">The generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var declarations = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) => ExtractDeclarations(ctx))
            .SelectMany(static (list, _) => list);

        var compilationAndDeclarations = context.CompilationProvider.Combine(declarations.Collect());

        context.RegisterSourceOutput(compilationAndDeclarations, static (spc, pair) =>
        {
            var (compilation, targets) = pair;
            ValidateAndGenerate(spc, compilation, targets);
        });
    }

    #endregion

    #region Attribute Detection & Parsing

    /// <summary>
    /// Extracts every <c>[RaisesEvent]</c> declaration from a type declaration's attributes.
    /// </summary>
    private static List<RaisesEventDeclaration> ExtractDeclarations(GeneratorSyntaxContext ctx)
    {
        var results = new List<RaisesEventDeclaration>();

        if (ctx.Node is not TypeDeclarationSyntax typeDeclaration)
            return results;

        var entitySymbol = ctx.SemanticModel.GetDeclaredSymbol(typeDeclaration) as INamedTypeSymbol;
        if (entitySymbol is null)
            return results;

        foreach (var attributeList in typeDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (!IsRaisesEventAttribute(attribute))
                    continue;

                var declaration = ExtractDeclaration(ctx, entitySymbol, attribute);
                if (declaration is not null)
                    results.Add(declaration);
            }
        }

        return results;
    }

    /// <summary>
    /// Checks if the attribute is a [RaisesEvent] attribute.
    /// </summary>
    private static bool IsRaisesEventAttribute(AttributeSyntax attribute)
    {
        var shortName = attribute.Name switch
        {
            IdentifierNameSyntax ins => ins.Identifier.Text,
            QualifiedNameSyntax qns => qns.Right.Identifier.Text,
            _ => null
        };

        return shortName is AttributeShortName or AttributeFullName;
    }

    /// <summary>
    /// Extracts the event type/label, operations, and narrowing properties from a [RaisesEvent] declaration.
    /// The first argument distinguishes the three ctor forms: <c>typeof(...)</c> is the type-naming form,
    /// an <c>EventOperations</c>-typed first argument is the label-less convention form, and anything else is
    /// treated as an attempted label convention form (validated later — the label may turn out to not be a
    /// compile-time constant string, which is itself a build error rather than "not a declaration").
    /// </summary>
    private static RaisesEventDeclaration? ExtractDeclaration(
        GeneratorSyntaxContext ctx, INamedTypeSymbol entitySymbol, AttributeSyntax attribute)
    {
        var arguments = attribute.ArgumentList?.Arguments ?? default;
        if (arguments.Count < 1)
            return null;

        var firstArgExpression = arguments[0].Expression;

        if (firstArgExpression is TypeOfExpressionSyntax typeOfExpression)
        {
            if (arguments.Count < 2)
                return null;

            var eventTypeSymbol = ctx.SemanticModel.GetTypeInfo(typeOfExpression.Type).Type as INamedTypeSymbol;

            return new RaisesEventDeclaration
            {
                EntitySymbol = entitySymbol,
                IsStringForm = false,
                EventTypeSymbol = eventTypeSymbol,
                Operations = ExtractOperations(ctx, arguments, 1),
                Properties = ExtractProperties(ctx, arguments, 2),
                Location = attribute.GetLocation(),
            };
        }

        // Label-less convention form: the first argument is the operations enum itself, not a label.
        if (ctx.SemanticModel.GetTypeInfo(firstArgExpression).Type?.Name == "EventOperations")
        {
            var operations = ExtractOperations(ctx, arguments, 0);
            var properties = ExtractProperties(ctx, arguments, 1);

            return new RaisesEventDeclaration
            {
                EntitySymbol = entitySymbol,
                IsStringForm = true,
                LabelIsConstantString = true,
                Label = null,
                Operations = operations,
                Properties = properties,
                ComposedName = EventNameComposer.Compose(entitySymbol.Name, null, properties, operations),
                Location = attribute.GetLocation(),
            };
        }

        if (arguments.Count < 2)
            return null;

        var constantValue = ctx.SemanticModel.GetConstantValue(firstArgExpression);
        var isConstantString = constantValue.HasValue && constantValue.Value is string;
        var label = isConstantString ? (string)constantValue.Value! : null;
        var labelOperations = ExtractOperations(ctx, arguments, 1);
        var labelProperties = ExtractProperties(ctx, arguments, 2);

        return new RaisesEventDeclaration
        {
            EntitySymbol = entitySymbol,
            IsStringForm = true,
            LabelIsConstantString = isConstantString,
            Label = label,
            Operations = labelOperations,
            Properties = labelProperties,
            ComposedName = EventNameComposer.Compose(entitySymbol.Name, label, labelProperties, labelOperations),
            Location = attribute.GetLocation(),
        };
    }

    /// <summary>
    /// Extracts the constant <c>EventOperations</c> value from the attribute argument at <paramref name="index"/>.
    /// </summary>
    private static int ExtractOperations(
        GeneratorSyntaxContext ctx, SeparatedSyntaxList<AttributeArgumentSyntax> arguments, int index)
    {
        var operationsValue = ctx.SemanticModel.GetConstantValue(arguments[index].Expression);
        return operationsValue.HasValue && operationsValue.Value is not null
            ? Convert.ToInt32(operationsValue.Value)
            : 0;
    }

    /// <summary>
    /// Extracts the narrowing property list from the trailing <c>params string[] properties</c> argument(s),
    /// starting at <paramref name="startIndex"/> and supporting both an explicit array/collection expression
    /// and individually-passed params values.
    /// </summary>
    private static List<string> ExtractProperties(
        GeneratorSyntaxContext ctx, SeparatedSyntaxList<AttributeArgumentSyntax> arguments, int startIndex)
    {
        var trailing = arguments.Skip(startIndex).Where(a => a.NameEquals is null).ToList();

        if (trailing.Count == 1 && trailing[0].Expression is ImplicitArrayCreationExpressionSyntax
            or ArrayCreationExpressionSyntax or CollectionExpressionSyntax)
        {
            return DtoGenerator.ExtractExcludedPropertiesFromExpression(ctx, trailing[0].Expression).ToList();
        }

        var result = new List<string>();
        foreach (var arg in trailing)
        {
            var constantValue = ctx.SemanticModel.GetConstantValue(arg.Expression);
            if (constantValue.HasValue && constantValue.Value is string propertyName)
                result.Add(propertyName);
        }

        return result;
    }

    #endregion

    #region Validation & Generation

    /// <summary>
    /// Validates every collected [RaisesEvent] declaration and, for valid convention-form declarations, emits
    /// their generated payload records.
    /// </summary>
    private static void ValidateAndGenerate(
        SourceProductionContext context, Compilation compilation, IReadOnlyList<RaisesEventDeclaration> targets)
    {
        var validConventionFormDeclarations = new List<RaisesEventDeclaration>();

        foreach (var declaration in targets)
        {
            ValidateNarrowing(context, declaration);

            if (declaration.Operations == 0)
            {
                ReportDiagnostic(context, "DKRAISEVT007", "No operation declared", DiagnosticSeverity.Error,
                    declaration.Location,
                    "Entity {0}: this [RaisesEvent] declaration names no operation; at least one operation must be named.",
                    declaration.EntitySymbol.Name);
                continue;
            }

            if (declaration.IsStringForm)
            {
                if (ValidateConventionForm(context, compilation, declaration))
                    validConventionFormDeclarations.Add(declaration);
            }
            else
            {
                ValidatePayloadEntity(context, declaration);
            }
        }

        GenerateStringFormRecords(context, compilation, validConventionFormDeclarations);
    }

    /// <summary>
    /// Validates narrowing property names and narrowing-without-Updated, identically for both declaration forms.
    /// </summary>
    private static void ValidateNarrowing(SourceProductionContext context, RaisesEventDeclaration decl)
    {
        if (decl.Properties.Count == 0)
            return;

        var entityProperties = DtoGenerator.GetEntityProperties(decl.EntitySymbol);

        foreach (var propertyName in decl.Properties)
        {
            if (propertyName.Contains('.'))
            {
                ReportDiagnostic(context, "DKRAISEVT001", "Invalid narrowing property", DiagnosticSeverity.Error,
                    decl.Location, "Entity {0}: narrowing property '{1}' is a nested path, which is not supported.",
                    decl.EntitySymbol.Name, propertyName);
                continue;
            }

            if (entityProperties.All(p => p.Name != propertyName))
            {
                ReportDiagnostic(context, "DKRAISEVT001", "Invalid narrowing property", DiagnosticSeverity.Error,
                    decl.Location, "Entity {0}: narrowing property '{1}' is not a property of the entity.",
                    decl.EntitySymbol.Name, propertyName);
            }
        }

        if ((decl.Operations & OperationUpdated) == 0)
        {
            ReportDiagnostic(context, "DKRAISEVT003", "Narrowing ignored", DiagnosticSeverity.Warning,
                decl.Location, "Entity {0}: narrowing is ignored because Operations has no Updated flag.",
                decl.EntitySymbol.Name);
        }
    }

    /// <summary>
    /// Validates that the named event type is a [GenerateDto] payload generated from the same entity that
    /// carries the [RaisesEvent] rule (type-naming form).
    /// </summary>
    private static void ValidatePayloadEntity(SourceProductionContext context, RaisesEventDeclaration decl)
    {
        if (decl.EventTypeSymbol is null)
            return;

        var generateDto = decl.EventTypeSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == GenerateDtoAttributeName);

        if (generateDto is null)
        {
            ReportDiagnostic(context, "DKRAISEVT002", "Payload entity mismatch", DiagnosticSeverity.Error,
                decl.Location,
                "Entity {0}: event type '{1}' does not carry [GenerateDto] and cannot be validated as a payload for this entity.",
                decl.EntitySymbol.Name, decl.EventTypeSymbol.Name);
            return;
        }

        if (generateDto.ConstructorArguments.Length == 0 ||
            generateDto.ConstructorArguments[0].Value is not ITypeSymbol payloadEntityType)
            return;

        if (!SymbolEqualityComparer.Default.Equals(payloadEntityType, decl.EntitySymbol))
        {
            ReportDiagnostic(context, "DKRAISEVT002", "Payload entity mismatch", DiagnosticSeverity.Error,
                decl.Location,
                "Entity {0}: event type '{1}' is generated from entity '{2}', not '{0}'.",
                decl.EntitySymbol.Name, decl.EventTypeSymbol.Name, payloadEntityType.Name);
        }
    }

    /// <summary>
    /// Validates a convention-form declaration: the label (when present) must be a compile-time constant, the
    /// composed name must be a single valid C# identifier, and it must not already resolve to an incompatible
    /// existing type. Returns <see langword="true"/> when the declaration is valid and should proceed to
    /// generation.
    /// </summary>
    private static bool ValidateConventionForm(
        SourceProductionContext context, Compilation compilation, RaisesEventDeclaration decl)
    {
        if (!decl.LabelIsConstantString)
        {
            // The label-less convention form always sets LabelIsConstantString to true at extraction — this
            // branch only fires for an attempted label expression that failed to fold to a constant.
            ReportDiagnostic(context, "DKRAISEVT005", "Label not a compile-time constant", DiagnosticSeverity.Error,
                decl.Location,
                "Entity {0}: the [RaisesEvent] label must be a compile-time constant string literal.",
                decl.EntitySymbol.Name);
            return false;
        }

        if (!SyntaxFacts.IsValidIdentifier(decl.ComposedName))
        {
            ReportDiagnostic(context, "DKRAISEVT005", "Event name not a valid identifier", DiagnosticSeverity.Error,
                decl.Location,
                "Entity {0}: the composed event name '{1}' is not a single valid C# identifier — the label cannot form part of an event record name.",
                decl.EntitySymbol.Name, decl.ComposedName);
            return false;
        }

        if (HasIncompatibleExistingType(compilation, decl.EntitySymbol, decl.ComposedName!, out var collidingType))
        {
            var guidance = IsGenerateDtoPayloadForEntity(collidingType!, decl.EntitySymbol)
                ? $"Use the type-naming form ([RaisesEvent(typeof({decl.ComposedName}), ...)]) instead, or change/add the label."
                : "Change or add the label so the declaration composes a different name.";

            ReportDiagnostic(context, "DKRAISEVT004", "Event name collides with existing type", DiagnosticSeverity.Error,
                decl.Location,
                "Entity {0}: '{1}' already resolves to an existing type. {2}",
                decl.EntitySymbol.Name, decl.ComposedName, guidance);
            return false;
        }

        return true;
    }

    /// <summary>
    /// Checks whether <paramref name="name"/> collides with a real, incompatible existing type in the entity's
    /// namespace. A hand-authored <c>public partial record</c> stub with the same name is NOT a collision — it
    /// is the developer's extension point for the generated record (identical to how <c>[GenerateDto]</c>
    /// payload records are extended) and simply merges with the generated partial via the compiler. Every other
    /// same-named type in the namespace — an interface/enum/delegate, an existing <c>[GenerateDto]</c> partial
    /// record, or a type that only exists in a referenced assembly — is a real collision.
    /// </summary>
    private static bool HasIncompatibleExistingType(
        Compilation compilation, INamedTypeSymbol entitySymbol, string name, out INamedTypeSymbol? collidingType)
    {
        var entityNamespace = GetEntityNamespace(entitySymbol);
        var qualifiedName = entityNamespace is null ? name : $"{entityNamespace}.{name}";

        var candidates = FindTypeSymbolsByNameAnyKind(compilation, name)
            .Where(t => GetEntityNamespace(t) == entityNamespace);

        var metadataType = compilation.GetTypeByMetadataName(qualifiedName);
        if (metadataType is not null)
            candidates = candidates.Append(metadataType);

        collidingType = candidates
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .FirstOrDefault(t => !IsCompatiblePartialRecordStub(t));

        return collidingType is not null;
    }

    /// <summary>
    /// True when <paramref name="type"/> is a <c>[GenerateDto]</c> payload record generated from
    /// <paramref name="entitySymbol"/> — the case where the type-naming form is a viable alternative remedy
    /// for a <c>DKRAISEVT004</c> collision.
    /// </summary>
    private static bool IsGenerateDtoPayloadForEntity(INamedTypeSymbol type, INamedTypeSymbol entitySymbol)
    {
        var generateDto = type.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == GenerateDtoAttributeName);

        return generateDto is not null &&
               generateDto.ConstructorArguments.Length > 0 &&
               generateDto.ConstructorArguments[0].Value is ITypeSymbol payloadEntityType &&
               SymbolEqualityComparer.Default.Equals(payloadEntityType, entitySymbol);
    }

    /// <summary>
    /// Finds every type symbol (class, struct, interface, enum, or delegate) declared in source and matching
    /// <paramref name="typeName"/> — unlike <see cref="DtoGenerator.FindTypeSymbolsByName"/>, which narrows to
    /// class/struct because it resolves entity types specifically.
    /// </summary>
    private static IEnumerable<INamedTypeSymbol> FindTypeSymbolsByNameAnyKind(Compilation compilation, string typeName) =>
        compilation
            .GetSymbolsWithName(n => n.Equals(typeName, StringComparison.Ordinal), SymbolFilter.Type)
            .OfType<INamedTypeSymbol>();

    /// <summary>
    /// True when <paramref name="type"/> is a plain hand-authored <c>partial record</c> stub — declared in
    /// source (never metadata-only), not itself a <c>[GenerateDto]</c> payload, and every declared part is
    /// <c>partial</c> — safe to merge the generated part into.
    /// </summary>
    private static bool IsCompatiblePartialRecordStub(INamedTypeSymbol type)
    {
        if (!type.IsRecord || type.DeclaringSyntaxReferences.IsEmpty)
            return false;

        if (type.GetAttributes().Any(a => a.AttributeClass?.Name == GenerateDtoAttributeName))
            return false;

        foreach (var syntaxRef in type.DeclaringSyntaxReferences)
        {
            if (syntaxRef.GetSyntax() is not TypeDeclarationSyntax typeDeclaration ||
                !typeDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
                return false;
        }

        return true;
    }

    /// <summary>
    /// Generates payload records for valid convention-form declarations, skipping (with a diagnostic) any
    /// composed name that two DIFFERENT entities in the same namespace both produce (<c>DKRAISEVT006</c>) or
    /// that more than one declaration on the SAME entity produces (<c>DKRAISEVT008</c>) — neither case is ever
    /// merged into one record.
    /// </summary>
    private static void GenerateStringFormRecords(
        SourceProductionContext context, Compilation compilation, List<RaisesEventDeclaration> declarations)
    {
        var groups = declarations.GroupBy(d => (Namespace: GetEntityNamespace(d.EntitySymbol), d.ComposedName));

        foreach (var group in groups)
        {
            var groupList = group.ToList();
            var distinctEntities = groupList
                .Select(d => d.EntitySymbol)
                .Distinct(SymbolEqualityComparer.Default)
                .Cast<INamedTypeSymbol>()
                .ToList();

            if (distinctEntities.Count > 1)
            {
                var entityNames = string.Join(", ", distinctEntities.Select(e => e.Name));
                foreach (var decl in groupList)
                {
                    ReportDiagnostic(context, "DKRAISEVT006", "Duplicate event name in namespace", DiagnosticSeverity.Error,
                        decl.Location,
                        "Event name '{0}' is declared by more than one entity in the same namespace ({1}). " +
                        "Rename one of the events — a duplicate name is never merged into a single record.",
                        group.Key.ComposedName, entityNames);
                }

                continue;
            }

            if (groupList.Count > 1)
            {
                foreach (var decl in groupList)
                {
                    ReportDiagnostic(context, "DKRAISEVT008", "Duplicate composed event name on entity", DiagnosticSeverity.Error,
                        decl.Location,
                        "Entity {0}: more than one [RaisesEvent] declaration composes to the same name '{1}'. " +
                        "Rename one — add or change its label, or its narrowing properties — so each declaration composes a distinct name.",
                        decl.EntitySymbol.Name, group.Key.ComposedName);
                }

                continue;
            }

            var declaration = groupList[0];
            var source = DtoGenerator.BuildRaisesEventRecordSource(
                declaration.EntitySymbol, declaration.ComposedName!, group.Key.Namespace, compilation);

            var hintName = $"{(group.Key.Namespace ?? "global")}.{declaration.ComposedName}.RaisesEvent.g.cs";
            context.AddSource(hintName, source);
        }
    }

    /// <summary>
    /// Gets the entity's namespace display string, or <see langword="null"/> for the global namespace.
    /// </summary>
    private static string? GetEntityNamespace(INamedTypeSymbol entitySymbol) =>
        entitySymbol.ContainingNamespace is { IsGlobalNamespace: false } ns ? ns.ToDisplayString() : null;

    /// <summary>
    /// Reports a diagnostic at the given location using a lazily-built descriptor.
    /// </summary>
    private static void ReportDiagnostic(
        SourceProductionContext context,
        string id,
        string title,
        DiagnosticSeverity severity,
        Location location,
        string messageFormat,
        params object?[] args)
    {
        var descriptor = new DiagnosticDescriptor(id, title, messageFormat, DiagnosticCategory, severity,
            isEnabledByDefault: true);
        context.ReportDiagnostic(Diagnostic.Create(descriptor, location, args));
    }

    #endregion

    #region Data Models

    /// <summary>
    /// A single <c>[RaisesEvent]</c> declaration found on an entity's syntax.
    /// </summary>
    private sealed record RaisesEventDeclaration
    {
        public INamedTypeSymbol EntitySymbol { get; set; } = null!;
        public bool IsStringForm { get; set; }
        public INamedTypeSymbol? EventTypeSymbol { get; set; }
        public bool LabelIsConstantString { get; set; }
        public string? Label { get; set; }
        public string? ComposedName { get; set; }
        public int Operations { get; set; }
        public List<string> Properties { get; set; } = [];
        public Location Location { get; set; } = Location.None;
    }

    #endregion
}
