<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <IsAspNetCoreApp>true</IsAspNetCoreApp>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>
    <ItemGroup>
        <None Include="..\..\NugetLogo.png" Pack="true" PackagePath="\"/>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentResults"/>
        <PackageReference Include="Asp.Versioning.Http"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="SharpGrip.FluentValidation.AutoValidation.Endpoints"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\SlimBus\DKNet.SlimBus.Extensions\DKNet.SlimBus.Extensions.csproj"/>
        <ProjectReference Include="..\..\EfCore\DKNet.EfCore.Specifications\DKNet.EfCore.Specifications.csproj"/>
    </ItemGroup>
</Project>
