// <auto-generated/> Value-equatable model records for DKNet.SlimBus.Generators.

using System.Collections.Immutable;
using System.Linq;

namespace DKNet.SlimBus.Generators;

#nullable enable

/// <summary>
/// A single constructor/method parameter that becomes a generated request property.
/// </summary>
/// <param name="Name">The original parameter name (e.g. <c>price</c>).</param>
/// <param name="PascalName">The parameter name with its first character upper-cased (e.g. <c>Price</c>).</param>
/// <param name="TypeFullName">The fully qualified C# type name for the property.</param>
/// <param name="AnnotationSources">
/// Source text of every <c>System.ComponentModel.DataAnnotations</c> attribute carried by the parameter,
/// reconstructed verbatim (e.g. <c>[global::System.ComponentModel.DataAnnotations.Required]</c>).
/// </param>
internal sealed record CrudParamModel(
    string Name,
    string PascalName,
    string TypeFullName,
    ImmutableArray<string> AnnotationSources)
{
    /// <inheritdoc />
    public bool Equals(CrudParamModel? other) =>
        other is not null &&
        Name == other.Name &&
        PascalName == other.PascalName &&
        TypeFullName == other.TypeFullName &&
        AnnotationSources.SequenceEqual(other.AnnotationSources);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        // System.HashCode is unavailable on netstandard2.0; combine manually (mirrors DtoGenerator.cs).
        unchecked
        {
            var hash = 17;
            hash = hash * 31 + Name.GetHashCode();
            hash = hash * 31 + PascalName.GetHashCode();
            hash = hash * 31 + TypeFullName.GetHashCode();
            foreach (var source in AnnotationSources) hash = hash * 31 + source.GetHashCode();
            return hash;
        }
    }
}

/// <summary>
/// A single <c>[CrudCreate]</c>/<c>[CrudUpdate]</c> member (constructor or method) resolved on an entity.
/// </summary>
/// <param name="RequestName">The generated request record's type name.</param>
/// <param name="MemberName">The member's name (<c>.ctor</c> for a constructor).</param>
/// <param name="IsConstructor"><see langword="true"/> when the member is the entity's constructor.</param>
/// <param name="Params">The member's parameters, in declaration order.</param>
internal sealed record CrudMemberModel(
    string RequestName,
    string MemberName,
    bool IsConstructor,
    ImmutableArray<CrudParamModel> Params)
{
    /// <inheritdoc />
    public bool Equals(CrudMemberModel? other) =>
        other is not null &&
        RequestName == other.RequestName &&
        MemberName == other.MemberName &&
        IsConstructor == other.IsConstructor &&
        Params.SequenceEqual(other.Params);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        unchecked
        {
            var hash = 17;
            hash = hash * 31 + RequestName.GetHashCode();
            hash = hash * 31 + MemberName.GetHashCode();
            hash = hash * 31 + IsConstructor.GetHashCode();
            foreach (var param in Params) hash = hash * 31 + param.GetHashCode();
            return hash;
        }
    }
}

/// <summary>
/// An entity discovered via <c>[CrudCreate]</c>/<c>[CrudUpdate]</c>, resolved against its DTO and key type,
/// ready for request-record emission.
/// </summary>
/// <param name="EntityFullName">The entity's fully qualified type name.</param>
/// <param name="EntityName">The entity's simple type name.</param>
/// <param name="KeyFullName">The fully qualified type name of the entity's <c>IEntity&lt;TKey&gt;</c> key.</param>
/// <param name="DtoFullName">The fully qualified type name of the entity's resolved <c>[GenerateDto]</c> DTO.</param>
/// <param name="DtoName">The DTO's simple type name.</param>
/// <param name="Create">The resolved <c>[CrudCreate]</c> member, or <see langword="null"/> when none is declared.</param>
/// <param name="Updates">The resolved <c>[CrudUpdate]</c> members, in declaration order.</param>
internal sealed record CrudEntityModel(
    string EntityFullName,
    string EntityName,
    string KeyFullName,
    string DtoFullName,
    string DtoName,
    CrudMemberModel? Create,
    ImmutableArray<CrudMemberModel> Updates)
{
    /// <inheritdoc />
    public bool Equals(CrudEntityModel? other) =>
        other is not null &&
        EntityFullName == other.EntityFullName &&
        EntityName == other.EntityName &&
        KeyFullName == other.KeyFullName &&
        DtoFullName == other.DtoFullName &&
        DtoName == other.DtoName &&
        Equals(Create, other.Create) &&
        Updates.SequenceEqual(other.Updates);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        unchecked
        {
            var hash = 17;
            hash = hash * 31 + EntityFullName.GetHashCode();
            hash = hash * 31 + EntityName.GetHashCode();
            hash = hash * 31 + KeyFullName.GetHashCode();
            hash = hash * 31 + DtoFullName.GetHashCode();
            hash = hash * 31 + DtoName.GetHashCode();
            hash = hash * 31 + (Create?.GetHashCode() ?? 0);
            foreach (var update in Updates) hash = hash * 31 + update.GetHashCode();
            return hash;
        }
    }
}
