// <auto-generated/> Roslyn incremental generator implementation for DKNet.SlimBus.Generators.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DKNet.SlimBus.Generators;

#nullable enable

/// <summary>
/// Incremental source generator that discovers entities carrying <c>[CrudCreate]</c>/<c>[CrudUpdate]</c>
/// members and emits a Create/Update request record for each, implementing the SlimBus request contracts.
/// Handler and endpoint emission are added by later generators layered on the same pipeline.
/// </summary>
[Generator]
public sealed class CrudGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Registers the compilation-driven pipeline: build the CRUD model for every compilation, then emit
    /// request records and diagnostics for it.
    /// </summary>
    /// <param name="context">The generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var results = context.CompilationProvider.Select(static (compilation, ct) => CrudModelBuilder.Build(compilation, ct));
        context.RegisterSourceOutput(results, static (spc, result) => Emitter.Emit(spc, result));
    }
}

/// <summary>
/// Diagnostic descriptors reported by <see cref="CrudModelBuilder"/>.
/// </summary>
internal static class CrudDiagnostics
{
    private const string Category = "DKNet.SlimBus.Generators";

    public static readonly DiagnosticDescriptor NoDtoFound = new(
        "DKCRUDGEN001",
        "No [GenerateDto] DTO found for CRUD entity",
        "Entity '{0}' has [CrudCreate]/[CrudUpdate] members but no [GenerateDto(typeof({0}))] DTO was found in the compiling project",
        Category, DiagnosticSeverity.Error, isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor MultipleDtosFound = new(
        "DKCRUDGEN002",
        "Multiple [GenerateDto] DTOs found for CRUD entity",
        "Entity '{0}' has more than one [GenerateDto(typeof({0}))] DTO in the compiling project",
        Category, DiagnosticSeverity.Error, isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor MultipleCrudCreate = new(
        "DKCRUDGEN003",
        "More than one [CrudCreate] member on entity",
        "Entity '{0}' has more than one member marked [CrudCreate]; only one is allowed",
        Category, DiagnosticSeverity.Error, isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor MemberNotPublic = new(
        "DKCRUDGEN004",
        "CRUD member is not public",
        "Member '{0}.{1}' is marked [CrudCreate]/[CrudUpdate] but is not public",
        Category, DiagnosticSeverity.Error, isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor EntityMissingIEntity = new(
        "DKCRUDGEN006",
        "Entity does not implement IEntity<TKey>",
        "Entity '{0}' has [CrudCreate]/[CrudUpdate] members but does not implement DKNet.EfCore.Abstractions.Entities.IEntity<TKey>",
        Category, DiagnosticSeverity.Error, isEnabledByDefault: true);
}

/// <summary>
/// The value-equatable output of <see cref="CrudModelBuilder.Build"/>: the resolved entities, the
/// diagnostics collected while resolving them, and the namespace generated requests are emitted into.
/// </summary>
internal sealed record CrudGenerationResult(
    ImmutableArray<CrudEntityModel> Entities,
    ImmutableArray<Diagnostic> Diagnostics,
    string Namespace)
{
    public bool Equals(CrudGenerationResult? other) =>
        other is not null &&
        Namespace == other.Namespace &&
        Entities.SequenceEqual(other.Entities) &&
        Diagnostics.SequenceEqual(other.Diagnostics);

    public override int GetHashCode()
    {
        // System.HashCode is unavailable on netstandard2.0; combine manually (mirrors DtoGenerator.cs).
        unchecked
        {
            var hash = 17;
            hash = hash * 31 + Namespace.GetHashCode();
            foreach (var entity in Entities) hash = hash * 31 + entity.GetHashCode();
            foreach (var diagnostic in Diagnostics) hash = hash * 31 + diagnostic.GetHashCode();
            return hash;
        }
    }
}

/// <summary>
/// Walks the compilation (and its referenced assemblies) for <c>[CrudCreate]</c>/<c>[CrudUpdate]</c>
/// members, resolves each hit entity's key and DTO, and produces the value-equatable model consumed by
/// <see cref="Emitter"/>.
/// </summary>
internal static class CrudModelBuilder
{
    private const string CrudCreateAttributeFullName = "DKNet.EfCore.Abstractions.Attributes.CrudCreateAttribute";
    private const string CrudUpdateAttributeFullName = "DKNet.EfCore.Abstractions.Attributes.CrudUpdateAttribute";
    private const string GenerateDtoAttributeFullName = "DKNet.EfCore.DtoGenerator.GenerateDtoAttribute";
    private const string EntityInterfaceNamespace = "DKNet.EfCore.Abstractions.Entities";
    private const string EntityInterfaceName = "IEntity";
    private const string DataAnnotationsNamespace = "System.ComponentModel.DataAnnotations";

    // Cheap name-prefix filter: skip framework and well-known third-party assemblies while walking
    // referenced assemblies for CRUD-attributed members.
    private static readonly string[] SkippedAssemblyPrefixes =
    [
        "System", "Microsoft", "netstandard", "mscorlib",
        "FluentResults", "Mapster", "SlimMessageBus", "Shouldly", "xunit"
    ];

    /// <summary>
    /// Builds the CRUD model for a compilation: every entity carrying <c>[CrudCreate]</c>/<c>[CrudUpdate]</c>
    /// members, resolved against its <c>IEntity&lt;TKey&gt;</c> key and its <c>[GenerateDto]</c> DTO, plus
    /// any diagnostics raised while resolving them.
    /// </summary>
    /// <param name="compilation">The compilation to scan.</param>
    /// <param name="ct">A cancellation token observed while walking assemblies and types.</param>
    /// <returns>The resolved entities, diagnostics, and target namespace for emission.</returns>
    public static CrudGenerationResult Build(Compilation compilation, CancellationToken ct)
    {
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var entities = ImmutableArray.CreateBuilder<CrudEntityModel>();

        // DTO resolution is scoped to the current compilation only (spec step 4).
        var dtoLookup = BuildDtoLookup(compilation.Assembly, ct);

        foreach (var assembly in EnumerateScannedAssemblies(compilation))
        {
            foreach (var type in GetAllTypes(assembly.GlobalNamespace))
            {
                ct.ThrowIfCancellationRequested();
                var model = TryBuildEntityModel(type, dtoLookup, diagnostics);
                if (model is not null) entities.Add(model);
            }
        }

        var ns = string.IsNullOrEmpty(compilation.AssemblyName) ? "Generated.Crud" : $"{compilation.AssemblyName}.Crud";
        return new CrudGenerationResult(entities.ToImmutable(), diagnostics.ToImmutable(), ns);
    }

    private static Dictionary<string, List<INamedTypeSymbol>> BuildDtoLookup(IAssemblySymbol assembly, CancellationToken ct)
    {
        var lookup = new Dictionary<string, List<INamedTypeSymbol>>(StringComparer.Ordinal);
        foreach (var type in GetAllTypes(assembly.GlobalNamespace))
        {
            ct.ThrowIfCancellationRequested();
            var attribute = GetAttribute(type, GenerateDtoAttributeFullName);
            if (attribute is null || attribute.ConstructorArguments.Length == 0) continue;
            if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol entity) continue;

            var key = entity.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (!lookup.TryGetValue(key, out var dtos))
            {
                dtos = [];
                lookup[key] = dtos;
            }

            dtos.Add(type);
        }

        return lookup;
    }

    private static CrudEntityModel? TryBuildEntityModel(
        INamedTypeSymbol type,
        Dictionary<string, List<INamedTypeSymbol>> dtoLookup,
        ImmutableArray<Diagnostic>.Builder diagnostics)
    {
        if (type.TypeKind is not (TypeKind.Class or TypeKind.Struct)) return null;

        var createCandidates = new List<(IMethodSymbol Member, AttributeData Attribute, bool IsConstructor)>();
        var updateMembers = ImmutableArray.CreateBuilder<CrudMemberModel>();
        var hasAnyCrudMember = false;

        foreach (var member in type.GetMembers())
        {
            if (member is not IMethodSymbol { MethodKind: MethodKind.Constructor or MethodKind.Ordinary } method) continue;
            var isConstructor = method.MethodKind == MethodKind.Constructor;

            var createAttribute = GetAttribute(method, CrudCreateAttributeFullName);
            if (createAttribute is not null)
            {
                hasAnyCrudMember = true;
                createCandidates.Add((method, createAttribute, isConstructor));
            }

            if (isConstructor) continue;

            var updateAttribute = GetAttribute(method, CrudUpdateAttributeFullName);
            if (updateAttribute is null) continue;

            hasAnyCrudMember = true;
            if (EnsurePublic(method, type, diagnostics))
                updateMembers.Add(BuildMemberModel(type, method, updateAttribute, isConstructor: false));
        }

        if (!hasAnyCrudMember) return null;

        CrudMemberModel? createMember = null;
        if (createCandidates.Count > 1)
        {
            diagnostics.Add(Diagnostic.Create(CrudDiagnostics.MultipleCrudCreate, Location.None, type.Name));
        }
        else if (createCandidates.Count == 1)
        {
            var (member, attribute, isConstructor) = createCandidates[0];
            if (EnsurePublic(member, type, diagnostics))
                createMember = BuildMemberModel(type, member, attribute, isConstructor);
        }

        var keyFullName = ResolveKeyFullName(type);
        if (keyFullName is null)
        {
            diagnostics.Add(Diagnostic.Create(CrudDiagnostics.EntityMissingIEntity, Location.None, type.Name));
            return null;
        }

        var entityKey = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (!dtoLookup.TryGetValue(entityKey, out var dtos) || dtos.Count == 0)
        {
            diagnostics.Add(Diagnostic.Create(CrudDiagnostics.NoDtoFound, Location.None, type.Name));
            return null;
        }

        if (dtos.Count > 1)
        {
            diagnostics.Add(Diagnostic.Create(CrudDiagnostics.MultipleDtosFound, Location.None, type.Name));
            return null;
        }

        var dto = dtos[0];
        return new CrudEntityModel(
            entityKey,
            type.Name,
            keyFullName,
            dto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            dto.Name,
            createMember,
            updateMembers.ToImmutable());
    }

    private static bool EnsurePublic(ISymbol member, INamedTypeSymbol type, ImmutableArray<Diagnostic>.Builder diagnostics)
    {
        if (member.DeclaredAccessibility == Accessibility.Public) return true;
        diagnostics.Add(Diagnostic.Create(CrudDiagnostics.MemberNotPublic, Location.None, type.Name, member.Name));
        return false;
    }

    private static CrudMemberModel BuildMemberModel(INamedTypeSymbol type, IMethodSymbol member, AttributeData attribute, bool isConstructor)
    {
        var overrideName = GetNamedArgString(attribute, "Name");
        var requestName = overrideName ?? (isConstructor
            ? $"Create{type.Name}Request"
            : $"{member.Name}{type.Name}Request");

        var parameters = ImmutableArray.CreateBuilder<CrudParamModel>();
        foreach (var parameter in member.Parameters)
            parameters.Add(BuildParamModel(parameter));

        return new CrudMemberModel(requestName, isConstructor ? ".ctor" : member.Name, isConstructor, parameters.ToImmutable());
    }

    private static CrudParamModel BuildParamModel(IParameterSymbol parameter)
    {
        var typeFullName = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var pascalName = ToPascalCase(parameter.Name);

        var annotations = ImmutableArray.CreateBuilder<string>();
        foreach (var attribute in parameter.GetAttributes())
        {
            var ns = attribute.AttributeClass?.ContainingNamespace?.ToDisplayString();
            if (ns is null || !ns.StartsWith(DataAnnotationsNamespace, StringComparison.Ordinal)) continue;
            annotations.Add(BuildAttributeSource(attribute));
        }

        return new CrudParamModel(parameter.Name, pascalName, typeFullName, annotations.ToImmutable());
    }

    private static string ToPascalCase(string name) =>
        string.IsNullOrEmpty(name) ? name : char.ToUpperInvariant(name[0]) + name.Substring(1);

    private static string BuildAttributeSource(AttributeData attribute)
    {
        var name = attribute.AttributeClass!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        // Conventional C# attribute usage drops the "Attribute" suffix (e.g. [Required], not [RequiredAttribute]).
        if (name.EndsWith("Attribute", StringComparison.Ordinal))
            name = name.Substring(0, name.Length - "Attribute".Length);
        var args = new List<string>();
        foreach (var arg in attribute.ConstructorArguments)
            args.Add(FormatTypedConstant(arg));
        foreach (var arg in attribute.NamedArguments)
            args.Add($"{arg.Key} = {FormatTypedConstant(arg.Value)}");

        return args.Count == 0 ? $"[{name}]" : $"[{name}({string.Join(", ", args)})]";
    }

    private static string FormatTypedConstant(TypedConstant constant)
    {
        if (constant.IsNull) return "null";
        return constant.Value switch
        {
            string s => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
            bool b => b ? "true" : "false",
            char c => "'" + c + "'",
            IFormattable f => f.ToString(null, CultureInfo.InvariantCulture),
            _ => constant.Value?.ToString() ?? "null"
        };
    }

    private static string? ResolveKeyFullName(INamedTypeSymbol type)
    {
        foreach (var iface in type.AllInterfaces)
        {
            var definition = iface.OriginalDefinition;
            if (definition.Arity == 1 && definition.Name == EntityInterfaceName &&
                definition.ContainingNamespace?.ToDisplayString() == EntityInterfaceNamespace)
            {
                return iface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }
        }

        return null;
    }

    private static AttributeData? GetAttribute(ISymbol symbol, string fullName) =>
        symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == fullName);

    private static string? GetNamedArgString(AttributeData attribute, string name)
    {
        foreach (var namedArgument in attribute.NamedArguments)
            if (namedArgument.Key == name) return namedArgument.Value.Value as string;
        return null;
    }

    private static IEnumerable<IAssemblySymbol> EnumerateScannedAssemblies(Compilation compilation)
    {
        yield return compilation.Assembly;
        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
            if (ShouldScan(assembly)) yield return assembly;
    }

    private static bool ShouldScan(IAssemblySymbol assembly)
    {
        var name = assembly.Identity.Name;
        foreach (var prefix in SkippedAssemblyPrefixes)
            if (name.StartsWith(prefix, StringComparison.Ordinal)) return false;
        return true;
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            yield return type;
            foreach (var nested in GetNestedTypes(type)) yield return nested;
        }

        foreach (var child in ns.GetNamespaceMembers())
        foreach (var type in GetAllTypes(child))
            yield return type;
    }

    private static IEnumerable<INamedTypeSymbol> GetNestedTypes(INamedTypeSymbol type)
    {
        foreach (var nested in type.GetTypeMembers())
        {
            yield return nested;
            foreach (var deeper in GetNestedTypes(nested)) yield return deeper;
        }
    }
}

/// <summary>
/// Emits the Create/Update request records (and diagnostics) for a <see cref="CrudGenerationResult"/>.
/// </summary>
internal static class Emitter
{
    private const string WitResponseInterface = "global::DKNet.SlimBus.Extensions.Fluents.Requests.IWitResponse<";
    private const string WithKeyInterface = "global::DKNet.SlimBus.Extensions.Fluents.Requests.IWithKey<";

    /// <summary>
    /// Reports the build's diagnostics and adds one generated source file per resolved entity.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="result">The model built by <see cref="CrudModelBuilder.Build"/>.</param>
    public static void Emit(SourceProductionContext context, CrudGenerationResult result)
    {
        foreach (var diagnostic in result.Diagnostics)
            context.ReportDiagnostic(diagnostic);

        foreach (var entity in result.Entities)
        {
            var source = BuildSource(entity, result.Namespace);
            context.AddSource($"{entity.EntityName}CrudRequests.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string BuildSource(CrudEntityModel entity, string ns)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by DKNet.SlimBus.Generators />");
        builder.AppendLine("#nullable enable");
        builder.Append("namespace ").Append(ns).AppendLine(";");
        builder.AppendLine();

        if (entity.Create is not null)
        {
            AppendCreateRequest(builder, entity, entity.Create);
            builder.AppendLine();
        }

        foreach (var update in entity.Updates)
        {
            AppendUpdateRequest(builder, entity, update);
            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static void AppendCreateRequest(StringBuilder builder, CrudEntityModel entity, CrudMemberModel member)
    {
        var doc = member.IsConstructor
            ? $"Create request generated from {entity.EntityName}'s [CrudCreate] constructor."
            : $"Create request generated from {entity.EntityName}.{member.MemberName}.";

        builder.Append("/// <summary>").Append(doc).AppendLine("</summary>");
        builder.Append("public sealed partial record ").Append(member.RequestName)
            .Append(" : ").Append(WitResponseInterface).Append(entity.DtoFullName).AppendLine(">");
        builder.AppendLine("{");
        AppendParams(builder, member, member.IsConstructor ? "constructor" : "method");
        builder.AppendLine("}");
    }

    private static void AppendUpdateRequest(StringBuilder builder, CrudEntityModel entity, CrudMemberModel member)
    {
        builder.Append("/// <summary>Update request generated from ")
            .Append(entity.EntityName).Append('.').Append(member.MemberName).AppendLine(".</summary>");
        builder.Append("public sealed partial record ").Append(member.RequestName).AppendLine(" :");
        builder.Append("    ").Append(WitResponseInterface).Append(entity.DtoFullName).AppendLine(">,");
        builder.Append("    ").Append(WithKeyInterface).Append(entity.KeyFullName).AppendLine(">");
        builder.AppendLine("{");
        builder.Append("    /// <summary>The target ").Append(entity.EntityName).AppendLine(" identifier (bound from route).</summary>");
        builder.Append("    public ").Append(entity.KeyFullName).AppendLine(" Id { get; set; }");
        builder.AppendLine();
        AppendParams(builder, member, "method");
        builder.AppendLine("}");
    }

    private static void AppendParams(StringBuilder builder, CrudMemberModel member, string parameterKind)
    {
        for (var i = 0; i < member.Params.Length; i++)
        {
            var param = member.Params[i];
            builder.Append("    /// <summary>Maps to ").Append(parameterKind).Append(" parameter '").Append(param.Name).AppendLine("'.</summary>");
            foreach (var annotation in param.AnnotationSources)
                builder.Append("    ").AppendLine(annotation);

            var isNullable = param.TypeFullName.EndsWith("?", StringComparison.Ordinal);
            builder.Append("    public ");
            if (!isNullable) builder.Append("required ");
            builder.Append(param.TypeFullName).Append(' ').Append(param.PascalName).AppendLine(" { get; init; }");

            if (i < member.Params.Length - 1) builder.AppendLine();
        }
    }
}
