// <auto-generated/> Roslyn incremental generator implementation for DKNet.SlimBus.Generators.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DKNet.SlimBus.Generators;

#nullable enable

/// <summary>
/// Incremental source generator that discovers entities carrying <c>[CrudCreate]</c>/<c>[CrudUpdate]</c>
/// members and emits a Create/Update request record for each, implementing the SlimBus request contracts.
/// Handler and endpoint emission are added by later generators layered on the same pipeline.
/// </summary>
[Generator]
public sealed class CrudGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Registers the compilation-driven pipeline: build the CRUD model for every compilation, then emit
    /// request records and diagnostics for it.
    /// </summary>
    /// <param name="context">The generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var results = context.CompilationProvider.Select(static (compilation, ct) => CrudModelBuilder.Build(compilation, ct));
        context.RegisterSourceOutput(results, static (spc, result) => Emitter.Emit(spc, result));
    }
}

/// <summary>
/// Diagnostic descriptors reported by <see cref="CrudModelBuilder"/>.
/// </summary>
internal static class CrudDiagnostics
{
    private const string Category = "DKNet.SlimBus.Generators";

    public static readonly DiagnosticDescriptor NoDtoFound = new(
        "DKCRUDGEN001",
        "No [GenerateDto] DTO found for CRUD entity",
        "Entity '{0}' has [CrudCreate]/[CrudUpdate] members but no [GenerateDto(typeof({0}))] DTO was found in the compiling project",
        Category, DiagnosticSeverity.Error, isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor MultipleDtosFound = new(
        "DKCRUDGEN002",
        "Multiple [GenerateDto] DTOs found for CRUD entity",
        "Entity '{0}' has more than one [GenerateDto(typeof({0}))] DTO in the compiling project",
        Category, DiagnosticSeverity.Error, isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor MultipleCrudCreate = new(
        "DKCRUDGEN003",
        "More than one [CrudCreate] member on entity",
        "Entity '{0}' has more than one member marked [CrudCreate]; only one is allowed",
        Category, DiagnosticSeverity.Error, isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor MemberNotPublic = new(
        "DKCRUDGEN004",
        "CRUD member is not public",
        "Member '{0}.{1}' is marked [CrudCreate]/[CrudUpdate] but is not public",
        Category, DiagnosticSeverity.Error, isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor HandWrittenHandlerOverride = new(
        "DKCRUDGEN005",
        "Hand-written handler overrides generated handler",
        "A hand-written type implementing IHandler<{0}, ...> was found; the generated handler for '{0}' was skipped",
        Category, DiagnosticSeverity.Info, isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor EntityMissingIEntity = new(
        "DKCRUDGEN006",
        "Entity does not implement IEntity<TKey>",
        "Entity '{0}' has [CrudCreate]/[CrudUpdate] members but does not implement DKNet.EfCore.Abstractions.Entities.IEntity<TKey>",
        Category, DiagnosticSeverity.Error, isEnabledByDefault: true);
}

/// <summary>
/// The value-equatable output of <see cref="CrudModelBuilder.Build"/>: the resolved entities, the
/// diagnostics collected while resolving them, and the namespace generated requests are emitted into.
/// </summary>
internal sealed record CrudGenerationResult(
    ImmutableArray<CrudEntityModel> Entities,
    ImmutableArray<Diagnostic> Diagnostics,
    string Namespace,
    bool EmitEndpoints)
{
    public bool Equals(CrudGenerationResult? other) =>
        other is not null &&
        Namespace == other.Namespace &&
        EmitEndpoints == other.EmitEndpoints &&
        Entities.SequenceEqual(other.Entities) &&
        Diagnostics.SequenceEqual(other.Diagnostics);

    public override int GetHashCode()
    {
        // System.HashCode is unavailable on netstandard2.0; combine manually (mirrors DtoGenerator.cs).
        unchecked
        {
            var hash = 17;
            hash = hash * 31 + Namespace.GetHashCode();
            hash = hash * 31 + EmitEndpoints.GetHashCode();
            foreach (var entity in Entities) hash = hash * 31 + entity.GetHashCode();
            foreach (var diagnostic in Diagnostics) hash = hash * 31 + diagnostic.GetHashCode();
            return hash;
        }
    }
}

/// <summary>
/// Walks the compilation (and its referenced assemblies) for <c>[CrudCreate]</c>/<c>[CrudUpdate]</c>
/// members, resolves each hit entity's key and DTO, and produces the value-equatable model consumed by
/// <see cref="Emitter"/>.
/// </summary>
internal static class CrudModelBuilder
{
    private const string CrudCreateAttributeFullName = "DKNet.EfCore.Abstractions.Attributes.CrudCreateAttribute";
    private const string CrudUpdateAttributeFullName = "DKNet.EfCore.Abstractions.Attributes.CrudUpdateAttribute";
    private const string GenerateDtoAttributeFullName = "DKNet.EfCore.DtoGenerator.GenerateDtoAttribute";
    private const string EntityInterfaceNamespace = "DKNet.EfCore.Abstractions.Entities";
    private const string EntityInterfaceName = "IEntity";
    private const string DataAnnotationsNamespace = "System.ComponentModel.DataAnnotations";

    // Cheap name-prefix filter: skip framework and well-known third-party assemblies while walking
    // referenced assemblies for CRUD-attributed members.
    private static readonly string[] SkippedAssemblyPrefixes =
    [
        "System", "Microsoft", "netstandard", "mscorlib",
        "FluentResults", "Mapster", "SlimMessageBus", "Shouldly", "xunit"
    ];

    /// <summary>
    /// Builds the CRUD model for a compilation: every entity carrying <c>[CrudCreate]</c>/<c>[CrudUpdate]</c>
    /// members, resolved against its <c>IEntity&lt;TKey&gt;</c> key and its <c>[GenerateDto]</c> DTO, plus
    /// any diagnostics raised while resolving them.
    /// </summary>
    /// <param name="compilation">The compilation to scan.</param>
    /// <param name="ct">A cancellation token observed while walking assemblies and types.</param>
    /// <returns>The resolved entities, diagnostics, and target namespace for emission.</returns>
    public static CrudGenerationResult Build(Compilation compilation, CancellationToken ct)
    {
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var entities = ImmutableArray.CreateBuilder<CrudEntityModel>();

        // DTO resolution is scoped to the current compilation only (spec step 4).
        var dtoLookup = BuildDtoLookup(compilation.Assembly, ct);

        // Hand-written handler overrides are looked up by the generated request's simple type name: the
        // request type itself is emitted by this same generator run, so it can never be resolved as a
        // symbol from this (pre-generation) compilation. Scanning syntax for a base-list entry naming
        // "IHandler<TRequest, ...>" textually is the only way to see the override before it exists.
        var handlerOverrides = FindHandWrittenHandlerOverrides(compilation, ct);

        foreach (var assembly in EnumerateScannedAssemblies(compilation))
        {
            foreach (var type in GetAllTypes(assembly.GlobalNamespace))
            {
                ct.ThrowIfCancellationRequested();
                var model = TryBuildEntityModel(type, dtoLookup, handlerOverrides, diagnostics);
                if (model is not null) entities.Add(model);
            }
        }

        var ns = string.IsNullOrEmpty(compilation.AssemblyName) ? "Generated.Crud" : $"{compilation.AssemblyName}.Crud";
        var emitEndpoints = ReferencesAspCoreExtensions(compilation);
        return new CrudGenerationResult(entities.ToImmutable(), diagnostics.ToImmutable(), ns, emitEndpoints);
    }

    // Endpoint-registration emission composes DKNet.AspCore.Extensions mappers (MapGetById, MapPost, ...);
    // consumers that only want requests/handlers (no ASP.NET Core dependency) must not have that file forced
    // on them, so it's skipped outright rather than emitted with unresolved types.
    private const string AspCoreExtensionsAssemblyName = "DKNet.AspCore.Extensions";

    private static bool ReferencesAspCoreExtensions(Compilation compilation)
    {
        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
            if (assembly.Identity.Name == AspCoreExtensionsAssemblyName) return true;
        return false;
    }

    private static Dictionary<string, List<INamedTypeSymbol>> BuildDtoLookup(IAssemblySymbol assembly, CancellationToken ct)
    {
        var lookup = new Dictionary<string, List<INamedTypeSymbol>>(StringComparer.Ordinal);
        foreach (var type in GetAllTypes(assembly.GlobalNamespace))
        {
            ct.ThrowIfCancellationRequested();
            var attribute = GetAttribute(type, GenerateDtoAttributeFullName);
            if (attribute is null || attribute.ConstructorArguments.Length == 0) continue;
            if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol entity) continue;

            var key = entity.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (!lookup.TryGetValue(key, out var dtos))
            {
                dtos = [];
                lookup[key] = dtos;
            }

            dtos.Add(type);
        }

        return lookup;
    }

    private static CrudEntityModel? TryBuildEntityModel(
        INamedTypeSymbol type,
        Dictionary<string, List<INamedTypeSymbol>> dtoLookup,
        Dictionary<string, Location> handlerOverrides,
        ImmutableArray<Diagnostic>.Builder diagnostics)
    {
        if (type.TypeKind is not (TypeKind.Class or TypeKind.Struct)) return null;

        var createCandidates = new List<(IMethodSymbol Member, AttributeData Attribute, bool IsConstructor)>();
        var updateMembers = ImmutableArray.CreateBuilder<CrudMemberModel>();
        var hasAnyCrudMember = false;

        foreach (var member in type.GetMembers())
        {
            if (member is not IMethodSymbol { MethodKind: MethodKind.Constructor or MethodKind.Ordinary } method) continue;
            var isConstructor = method.MethodKind == MethodKind.Constructor;

            var createAttribute = GetAttribute(method, CrudCreateAttributeFullName);
            if (createAttribute is not null)
            {
                hasAnyCrudMember = true;
                createCandidates.Add((method, createAttribute, isConstructor));
            }

            if (isConstructor) continue;

            var updateAttribute = GetAttribute(method, CrudUpdateAttributeFullName);
            if (updateAttribute is null) continue;

            hasAnyCrudMember = true;
            if (EnsurePublic(method, type, diagnostics))
                updateMembers.Add(BuildMemberModel(type, method, updateAttribute, isConstructor: false, handlerOverrides, diagnostics));
        }

        if (!hasAnyCrudMember) return null;

        CrudMemberModel? createMember = null;
        if (createCandidates.Count > 1)
        {
            diagnostics.Add(Diagnostic.Create(CrudDiagnostics.MultipleCrudCreate, Location.None, type.Name));
        }
        else if (createCandidates.Count == 1)
        {
            var (member, attribute, isConstructor) = createCandidates[0];
            if (EnsurePublic(member, type, diagnostics))
                createMember = BuildMemberModel(type, member, attribute, isConstructor, handlerOverrides, diagnostics);
        }

        var keyFullName = ResolveKeyFullName(type);
        if (keyFullName is null)
        {
            diagnostics.Add(Diagnostic.Create(CrudDiagnostics.EntityMissingIEntity, Location.None, type.Name));
            return null;
        }

        var entityKey = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (!dtoLookup.TryGetValue(entityKey, out var dtos) || dtos.Count == 0)
        {
            diagnostics.Add(Diagnostic.Create(CrudDiagnostics.NoDtoFound, Location.None, type.Name));
            return null;
        }

        if (dtos.Count > 1)
        {
            diagnostics.Add(Diagnostic.Create(CrudDiagnostics.MultipleDtosFound, Location.None, type.Name));
            return null;
        }

        var dto = dtos[0];
        return new CrudEntityModel(
            entityKey,
            type.Name,
            keyFullName,
            dto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            dto.Name,
            createMember,
            updateMembers.ToImmutable());
    }

    private static bool EnsurePublic(ISymbol member, INamedTypeSymbol type, ImmutableArray<Diagnostic>.Builder diagnostics)
    {
        if (member.DeclaredAccessibility == Accessibility.Public) return true;
        diagnostics.Add(Diagnostic.Create(CrudDiagnostics.MemberNotPublic, Location.None, type.Name, member.Name));
        return false;
    }

    private static CrudMemberModel BuildMemberModel(
        INamedTypeSymbol type,
        IMethodSymbol member,
        AttributeData attribute,
        bool isConstructor,
        Dictionary<string, Location> handlerOverrides,
        ImmutableArray<Diagnostic>.Builder diagnostics)
    {
        var overrideName = GetNamedArgString(attribute, "Name");
        var requestName = overrideName ?? (isConstructor
            ? $"Create{type.Name}Request"
            : $"{member.Name}{type.Name}Request");

        var parameters = ImmutableArray.CreateBuilder<CrudParamModel>();
        foreach (var parameter in member.Parameters)
            parameters.Add(BuildParamModel(parameter));

        var hasHandWrittenHandler = handlerOverrides.TryGetValue(requestName, out var overrideLocation);
        if (hasHandWrittenHandler)
            diagnostics.Add(Diagnostic.Create(CrudDiagnostics.HandWrittenHandlerOverride, overrideLocation, requestName));

        return new CrudMemberModel(
            requestName, isConstructor ? ".ctor" : member.Name, isConstructor, parameters.ToImmutable(), hasHandWrittenHandler);
    }

    /// <summary>
    /// Scans the current compilation's own syntax trees (never referenced assemblies, which have no
    /// syntax) for a type declaration whose base list names <c>IHandler&lt;TRequest, TResponse&gt;</c>,
    /// keyed by <c>TRequest</c>'s simple name. Purely syntactic because the generated request type this
    /// is matched against does not exist as a symbol in this (pre-generation) compilation.
    /// </summary>
    private static Dictionary<string, Location> FindHandWrittenHandlerOverrides(Compilation compilation, CancellationToken ct)
    {
        var overrides = new Dictionary<string, Location>(StringComparer.Ordinal);

        foreach (var tree in compilation.SyntaxTrees)
        {
            ct.ThrowIfCancellationRequested();
            foreach (var typeDeclaration in tree.GetRoot(ct).DescendantNodes().OfType<TypeDeclarationSyntax>())
            {
                if (typeDeclaration.BaseList is null) continue;

                foreach (var baseType in typeDeclaration.BaseList.Types)
                {
                    var handlerGeneric = AsIHandlerGeneric(baseType.Type);
                    if (handlerGeneric is null || handlerGeneric.TypeArgumentList.Arguments.Count != 2) continue;

                    var requestName = SimpleTypeName(handlerGeneric.TypeArgumentList.Arguments[0]);
                    if (requestName is not null)
                        overrides[requestName] = typeDeclaration.Identifier.GetLocation();
                }
            }
        }

        return overrides;
    }

    // Unwraps a (possibly qualified, e.g. "Fluents.Requests.IHandler<...>") base-type reference down to
    // its generic name, when that name is "IHandler".
    private static GenericNameSyntax? AsIHandlerGeneric(TypeSyntax type) =>
        type switch
        {
            GenericNameSyntax { Identifier.Text: "IHandler" } generic => generic,
            QualifiedNameSyntax qualified => AsIHandlerGeneric(qualified.Right),
            _ => null
        };

    // The simple (unqualified, non-generic) name of a type-argument syntax node, e.g. "CreateProductRequest"
    // from "MyApi.CreateProductRequest" or plain "CreateProductRequest".
    private static string? SimpleTypeName(TypeSyntax type) =>
        type switch
        {
            IdentifierNameSyntax identifier => identifier.Identifier.Text,
            GenericNameSyntax generic => generic.Identifier.Text,
            QualifiedNameSyntax qualified => SimpleTypeName(qualified.Right),
            AliasQualifiedNameSyntax alias => SimpleTypeName(alias.Name),
            _ => null
        };

    private static CrudParamModel BuildParamModel(IParameterSymbol parameter)
    {
        var typeFullName = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var pascalName = ToPascalCase(parameter.Name);

        var annotations = ImmutableArray.CreateBuilder<string>();
        foreach (var attribute in parameter.GetAttributes())
        {
            var ns = attribute.AttributeClass?.ContainingNamespace?.ToDisplayString();
            if (ns is null || !ns.StartsWith(DataAnnotationsNamespace, StringComparison.Ordinal)) continue;
            annotations.Add(BuildAttributeSource(attribute));
        }

        return new CrudParamModel(parameter.Name, pascalName, typeFullName, annotations.ToImmutable());
    }

    private static string ToPascalCase(string name) =>
        string.IsNullOrEmpty(name) ? name : char.ToUpperInvariant(name[0]) + name.Substring(1);

    private static string BuildAttributeSource(AttributeData attribute)
    {
        var name = attribute.AttributeClass!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        // Conventional C# attribute usage drops the "Attribute" suffix (e.g. [Required], not [RequiredAttribute]).
        if (name.EndsWith("Attribute", StringComparison.Ordinal))
            name = name.Substring(0, name.Length - "Attribute".Length);
        var args = new List<string>();
        foreach (var arg in attribute.ConstructorArguments)
            args.Add(FormatTypedConstant(arg));
        foreach (var arg in attribute.NamedArguments)
            args.Add($"{arg.Key} = {FormatTypedConstant(arg.Value)}");

        return args.Count == 0 ? $"[{name}]" : $"[{name}({string.Join(", ", args)})]";
    }

    private static string FormatTypedConstant(TypedConstant constant)
    {
        if (constant.IsNull) return "null";
        switch (constant.Kind)
        {
            case TypedConstantKind.Type:
                var typeArg = (ITypeSymbol)constant.Value!;
                return $"typeof({typeArg.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})";
            case TypedConstantKind.Enum:
                return FormatEnumConstant(constant);
            case TypedConstantKind.Array:
                return "new[] { " + string.Join(", ", constant.Values.Select(FormatTypedConstant)) + " }";
            default:
                return constant.Value switch
                {
                    string s => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
                    bool b => b ? "true" : "false",
                    char c => "'" + c + "'",
                    IFormattable f => f.ToString(null, CultureInfo.InvariantCulture),
                    _ => constant.Value?.ToString() ?? "null"
                };
        }
    }

    private static string FormatEnumConstant(TypedConstant constant)
    {
        var enumTypeName = constant.Type?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "int";
        if (constant.Type is INamedTypeSymbol enumType && constant.Value is not null)
        {
            foreach (var member in enumType.GetMembers().OfType<IFieldSymbol>())
            {
                if (member.HasConstantValue && Equals(member.ConstantValue, constant.Value))
                    return $"{enumTypeName}.{member.Name}";
            }
        }

        // Combined flags or an unmatched value: cast the underlying literal.
        return $"({enumTypeName}){constant.Value}";
    }

    private static string? ResolveKeyFullName(INamedTypeSymbol type)
    {
        foreach (var iface in type.AllInterfaces)
        {
            var definition = iface.OriginalDefinition;
            if (definition.Arity == 1 && definition.Name == EntityInterfaceName &&
                definition.ContainingNamespace?.ToDisplayString() == EntityInterfaceNamespace)
            {
                return iface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }
        }

        return null;
    }

    private static AttributeData? GetAttribute(ISymbol symbol, string fullName) =>
        symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == fullName);

    private static string? GetNamedArgString(AttributeData attribute, string name)
    {
        foreach (var namedArgument in attribute.NamedArguments)
            if (namedArgument.Key == name) return namedArgument.Value.Value as string;
        return null;
    }

    private static IEnumerable<IAssemblySymbol> EnumerateScannedAssemblies(Compilation compilation)
    {
        yield return compilation.Assembly;
        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
            if (ShouldScan(assembly)) yield return assembly;
    }

    private static bool ShouldScan(IAssemblySymbol assembly)
    {
        var name = assembly.Identity.Name;
        foreach (var prefix in SkippedAssemblyPrefixes)
            // Exact name or dot-prefixed namespace only — a plain StartsWith would also skip a user
            // assembly like "Systemic.Domain" or "MicrosoftX.Domain".
            if (name == prefix || name.StartsWith(prefix + ".", StringComparison.Ordinal)) return false;
        return true;
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            yield return type;
            foreach (var nested in GetNestedTypes(type)) yield return nested;
        }

        foreach (var child in ns.GetNamespaceMembers())
        foreach (var type in GetAllTypes(child))
            yield return type;
    }

    private static IEnumerable<INamedTypeSymbol> GetNestedTypes(INamedTypeSymbol type)
    {
        foreach (var nested in type.GetTypeMembers())
        {
            yield return nested;
            foreach (var deeper in GetNestedTypes(nested)) yield return deeper;
        }
    }
}

/// <summary>
/// Emits the Create/Update request records (and diagnostics) for a <see cref="CrudGenerationResult"/>.
/// </summary>
internal static class Emitter
{
    private const string WitResponseInterface = "global::DKNet.SlimBus.Extensions.Fluents.Requests.IWitResponse<";
    private const string WithKeyInterface = "global::DKNet.SlimBus.Extensions.Fluents.Requests.IWithKey<";

    /// <summary>
    /// Reports the build's diagnostics and adds one generated source file per resolved entity.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="result">The model built by <see cref="CrudModelBuilder.Build"/>.</param>
    public static void Emit(SourceProductionContext context, CrudGenerationResult result)
    {
        foreach (var diagnostic in result.Diagnostics)
            context.ReportDiagnostic(diagnostic);

        foreach (var entity in result.Entities)
        {
            var source = BuildSource(entity, result.Namespace);
            context.AddSource($"{entity.EntityName}CrudRequests.g.cs", SourceText.From(source, Encoding.UTF8));

            var handlersSource = BuildHandlersSource(entity, result.Namespace);
            if (handlersSource is not null)
                context.AddSource($"{entity.EntityName}CrudHandlers.g.cs", SourceText.From(handlersSource, Encoding.UTF8));

            if (result.EmitEndpoints)
            {
                var endpointsSource = BuildEndpointsSource(entity, result.Namespace);
                context.AddSource($"{entity.EntityName}CrudEndpoints.g.cs", SourceText.From(endpointsSource, Encoding.UTF8));
            }
        }
    }

    private static string BuildSource(CrudEntityModel entity, string ns)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by DKNet.SlimBus.Generators />");
        builder.AppendLine("#nullable enable");
        builder.Append("namespace ").Append(ns).AppendLine(";");
        builder.AppendLine();

        if (entity.Create is not null)
        {
            AppendCreateRequest(builder, entity, entity.Create);
            builder.AppendLine();
        }

        foreach (var update in entity.Updates)
        {
            AppendUpdateRequest(builder, entity, update);
            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static void AppendCreateRequest(StringBuilder builder, CrudEntityModel entity, CrudMemberModel member)
    {
        var doc = member.IsConstructor
            ? $"Create request generated from {entity.EntityName}'s [CrudCreate] constructor."
            : $"Create request generated from {entity.EntityName}.{member.MemberName}.";

        builder.Append("/// <summary>").Append(doc).AppendLine("</summary>");
        builder.Append("public sealed partial record ").Append(member.RequestName)
            .Append(" : ").Append(WitResponseInterface).Append(entity.DtoFullName).AppendLine(">");
        builder.AppendLine("{");
        AppendParams(builder, member, member.IsConstructor ? "constructor" : "method");
        builder.AppendLine("}");
    }

    private static void AppendUpdateRequest(StringBuilder builder, CrudEntityModel entity, CrudMemberModel member)
    {
        builder.Append("/// <summary>Update request generated from ")
            .Append(entity.EntityName).Append('.').Append(member.MemberName).AppendLine(".</summary>");
        builder.Append("public sealed partial record ").Append(member.RequestName).AppendLine(" :");
        builder.Append("    ").Append(WitResponseInterface).Append(entity.DtoFullName).AppendLine(">,");
        builder.Append("    ").Append(WithKeyInterface).Append(entity.KeyFullName).AppendLine(">");
        builder.AppendLine("{");
        builder.Append("    /// <summary>The target ").Append(entity.EntityName).AppendLine(" identifier (bound from route).</summary>");
        builder.Append("    public ").Append(entity.KeyFullName).AppendLine(" Id { get; set; }");
        builder.AppendLine();
        AppendParams(builder, member, "method");
        builder.AppendLine("}");
    }

    private static void AppendParams(StringBuilder builder, CrudMemberModel member, string parameterKind)
    {
        for (var i = 0; i < member.Params.Length; i++)
        {
            var param = member.Params[i];
            builder.Append("    /// <summary>Maps to ").Append(parameterKind).Append(" parameter '").Append(param.Name).AppendLine("'.</summary>");
            foreach (var annotation in param.AnnotationSources)
                builder.Append("    ").AppendLine(annotation);

            var isNullable = param.TypeFullName.EndsWith("?", StringComparison.Ordinal);
            builder.Append("    public ");
            if (!isNullable) builder.Append("required ");
            builder.Append(param.TypeFullName).Append(' ').Append(param.PascalName).AppendLine(" { get; init; }");

            if (i < member.Params.Length - 1) builder.AppendLine();
        }
    }

    /// <summary>
    /// Builds the handlers file for an entity, or <see langword="null"/> when every one of its
    /// Create/Update members already has a hand-written <c>IHandler</c> (see <see cref="CrudMemberModel.HasHandWrittenHandler"/>).
    /// </summary>
    private static string? BuildHandlersSource(CrudEntityModel entity, string ns)
    {
        var emitCreate = entity.Create is not null && !entity.Create.HasHandWrittenHandler;
        var updatesToEmit = entity.Updates.Where(u => !u.HasHandWrittenHandler).ToImmutableArray();
        if (!emitCreate && updatesToEmit.Length == 0) return null;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by DKNet.SlimBus.Generators />");
        builder.AppendLine("#nullable enable");
        // Only update handlers call the IRepositorySpec.FirstOrDefaultAsync extension member; it's only
        // reachable via extension-invocation syntax (repository.FirstOrDefaultAsync(...)), which needs its
        // declaring namespace in scope.
        if (updatesToEmit.Length > 0)
            builder.AppendLine("using DKNet.EfCore.Specifications.Extensions;");
        builder.Append("namespace ").Append(ns).AppendLine(";");
        builder.AppendLine();

        if (updatesToEmit.Length > 0)
        {
            AppendByIdSpec(builder, entity);
            builder.AppendLine();
        }

        if (emitCreate)
        {
            AppendCreateHandler(builder, entity, entity.Create!);
            builder.AppendLine();
        }

        foreach (var update in updatesToEmit)
        {
            AppendUpdateHandler(builder, entity, update);
            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static void AppendByIdSpec(StringBuilder builder, CrudEntityModel entity)
    {
        builder.Append("/// <summary>Matches a single ").Append(entity.EntityName)
            .AppendLine(" by id; used by this file's generated update handlers to fetch the entity.</summary>");
        builder.Append("file sealed class ").Append(entity.EntityName).Append("ByIdCrudSpec : global::DKNet.EfCore.Specifications.Definitions.Specification<")
            .Append(entity.EntityFullName).AppendLine(">");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>Initializes the specification with a filter matching the given id.</summary>");
        builder.Append("    public ").Append(entity.EntityName).Append("ByIdCrudSpec(").Append(entity.KeyFullName)
            .AppendLine(" id) => WithFilter(x => x.Id.Equals(id));");
        builder.AppendLine("}");
    }

    private static void AppendCreateHandler(StringBuilder builder, CrudEntityModel entity, CrudMemberModel member)
    {
        var handlerName = ToHandlerName(member.RequestName);
        builder.Append("/// <summary>Generated create handler for ").Append(entity.EntityName)
            .AppendLine(". Write a class implementing the same IHandler to replace it.</summary>");
        AppendHandlerHeader(builder, handlerName, member, entity);
        builder.AppendLine("    {");
        builder.Append("        var entity = new ").Append(entity.EntityFullName).Append('(')
            .Append(string.Join(", ", member.Params.Select(p => "request." + p.PascalName))).AppendLine(");");
        builder.AppendLine("        await repository.AddAsync(entity, cancellationToken);");
        AppendReturnMappedResult(builder, entity);
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    private static void AppendUpdateHandler(StringBuilder builder, CrudEntityModel entity, CrudMemberModel member)
    {
        var handlerName = ToHandlerName(member.RequestName);
        builder.Append("/// <summary>Generated update handler for ").Append(entity.EntityName).Append('.')
            .Append(member.MemberName).AppendLine(". Write a class implementing the same IHandler to replace it.</summary>");
        AppendHandlerHeader(builder, handlerName, member, entity);
        builder.AppendLine("    {");
        builder.Append("        var entity = await repository.FirstOrDefaultAsync(new ").Append(entity.EntityName)
            .AppendLine("ByIdCrudSpec(request.Id), cancellationToken);");
        builder.AppendLine("        if (entity is null)");
        builder.Append("            return global::FluentResults.Result.Fail<").Append(entity.DtoFullName).AppendLine(">(");
        builder.Append("                new global::DKNet.SlimBus.Extensions.NotFoundError($\"").Append(entity.EntityName)
            .AppendLine(" '{request.Id}' was not found.\"));");
        builder.Append("        entity.").Append(member.MemberName).Append('(')
            .Append(string.Join(", ", member.Params.Select(p => "request." + p.PascalName))).AppendLine(");");
        AppendReturnMappedResult(builder, entity);
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    private static void AppendHandlerHeader(StringBuilder builder, string handlerName, CrudMemberModel member, CrudEntityModel entity)
    {
        builder.Append("internal sealed class ").Append(handlerName).AppendLine("(");
        builder.AppendLine("    global::DKNet.EfCore.Specifications.Repositories.IRepositorySpec repository,");
        builder.AppendLine("    global::MapsterMapper.IMapper mapper)");
        builder.Append("    : global::DKNet.SlimBus.Extensions.Fluents.Requests.IHandler<").Append(member.RequestName)
            .Append(", ").Append(entity.DtoFullName).AppendLine(">");
        builder.AppendLine("{");
        builder.AppendLine("    /// <inheritdoc />");
        builder.Append("    public async global::System.Threading.Tasks.Task<global::FluentResults.IResult<")
            .Append(entity.DtoFullName).AppendLine(">> OnHandle(");
        builder.Append("        ").Append(member.RequestName)
            .AppendLine(" request, global::System.Threading.CancellationToken cancellationToken)");
    }

    private static void AppendReturnMappedResult(StringBuilder builder, CrudEntityModel entity)
    {
        builder.Append("        return global::DKNet.SlimBus.Extensions.LazyMapper.LazyMapExtensions.ResultOf<")
            .Append(entity.DtoFullName).AppendLine(">(mapper, entity);");
    }

    private static string ToHandlerName(string requestName) =>
        requestName.EndsWith("Request", StringComparison.Ordinal)
            ? requestName.Substring(0, requestName.Length - "Request".Length) + "Handler"
            : requestName + "Handler";

    /// <summary>
    /// Builds the <c>Map{Entity}Crud</c> endpoint-registration extension for an entity, composing the
    /// existing <c>DKNet.AspCore.Extensions</c> mappers over the entity's resolved key/DTO and generated
    /// Create/Update requests.
    /// </summary>
    private static string BuildEndpointsSource(CrudEntityModel entity, string ns)
    {
        const string optionsType = "global::DKNet.AspCore.Extensions.Endpoints.CrudMapOptions";
        const string opType = "global::DKNet.AspCore.Extensions.Endpoints.CrudOp";
        const string groupType = "global::Microsoft.AspNetCore.Routing.RouteGroupBuilder";

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by DKNet.SlimBus.Generators />");
        builder.AppendLine("#nullable enable");
        // FluentsEntityEndpointMapperExtensions/FluentsEndpointMapperExtensions declare their MapXxx
        // members as C# 14 `extension(RouteGroupBuilder)` blocks; this using brings them into scope so
        // the extension-invocation syntax below (group.MapGetById<...>()) resolves.
        builder.AppendLine("using DKNet.AspCore.Extensions.Endpoints;");
        builder.Append("namespace ").Append(ns).AppendLine(";");
        builder.AppendLine();

        builder.Append("/// <summary>Registers the generated CRUD endpoints for ").Append(entity.EntityName).AppendLine(".</summary>");
        builder.Append("public static class ").Append(entity.EntityName).AppendLine("CrudEndpointExtensions");
        builder.AppendLine("{");
        builder.Append("    /// <summary>Maps GET {id}, GET /, POST /, PUT {id} (per update request) and DELETE {id} for ")
            .Append(entity.EntityName).AppendLine(".</summary>");
        builder.Append("    public static ").Append(groupType).Append(" Map").Append(entity.EntityName).AppendLine("Crud(");
        builder.Append("        this ").Append(groupType).AppendLine(" group,");
        builder.Append("        global::System.Action<").Append(optionsType).AppendLine(">? configure = null)");
        builder.AppendLine("    {");
        builder.Append("        var options = new ").Append(optionsType).AppendLine("();");
        builder.AppendLine("        configure?.Invoke(options);");

        AppendMapCall(builder, opType, "GetById",
            $"group.MapGetById<{entity.EntityFullName}, {entity.KeyFullName}, {entity.DtoFullName}>();");
        AppendMapCall(builder, opType, "GetList",
            $"group.MapGetList<{entity.EntityFullName}, {entity.KeyFullName}, {entity.DtoFullName}>();");
        AppendMapCall(builder, opType, "Delete",
            $"group.MapDeleteById<{entity.EntityFullName}, {entity.KeyFullName}>();");

        if (entity.Create is not null)
            AppendMapCall(builder, opType, "Create",
                $"group.MapPost<{entity.Create.RequestName}, {entity.DtoFullName}>(\"/\");");

        for (var i = 0; i < entity.Updates.Length; i++)
        {
            var update = entity.Updates[i];
            var route = i == 0 ? "{id}" : $"{{id}}/{ToKebabCase(update.MemberName)}";
            AppendMapCall(builder, opType, "Update",
                $"group.MapPutById<{update.RequestName}, {entity.KeyFullName}, {entity.DtoFullName}>(\"{route}\");");
        }

        builder.AppendLine("        return group;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendMapCall(StringBuilder builder, string opType, string op, string mapCallStatement)
    {
        builder.Append("        if (!options.IsExcluded(").Append(opType).Append('.').Append(op).AppendLine("))");
        builder.Append("            ").AppendLine(mapCallStatement);
    }

    // "UpdatePrice" -> "update-price". Used only for the second-and-later [CrudUpdate] route segment
    // (task spec: first update maps to "{id}", each additional to "{id}/{kebab-case-method-name}").
    private static string ToKebabCase(string memberName)
    {
        var builder = new StringBuilder();
        for (var i = 0; i < memberName.Length; i++)
        {
            var c = memberName[i];
            if (char.IsUpper(c))
            {
                if (i > 0) builder.Append('-');
                builder.Append(char.ToLowerInvariant(c));
            }
            else
            {
                builder.Append(c);
            }
        }

        return builder.ToString();
    }
}
