// <auto-generated/> Roslyn incremental generator implementation for DKNet.SlimBus.Generators.

using Microsoft.CodeAnalysis;

namespace DKNet.SlimBus.Generators;

#nullable enable

/// <summary>
/// Incremental source generator that discovers entities carrying <c>[CrudCreate]</c>/<c>[CrudUpdate]</c>
/// members and emits a Create/Update request record for each, implementing the SlimBus request contracts.
/// Handler and endpoint emission are added by later generators layered on the same pipeline.
/// </summary>
[Generator]
public sealed class CrudGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Registers the generator's pipeline.
    /// </summary>
    /// <param name="context">The generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Scaffold only: discovery, DTO resolution, and request emission are added next.
    }
}
