// <auto-generated/> netstandard2.0 polyfill enabling C# record/init syntax in this generator project.

namespace System.Runtime.CompilerServices;

#nullable enable

/// <summary>
/// Polyfill required for C# 9+ <c>record</c> types and <c>init</c> accessors to compile against
/// netstandard2.0, which does not ship this type in its reference assemblies.
/// </summary>
internal static class IsExternalInit;
