// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
using DKNet.EfCore.DtoEntities.Share;

namespace DKNet.EfCore.DtoGenerator.Tests.Features.StaticData.ChannelDatas;

/// <summary>
/// Generated DTO for entity ChannelData.
/// </summary>
public partial record ChannelDto
{
}
