// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
using System.ComponentModel.DataAnnotations;

namespace DKNet.EfCore.DtoGenerator.Tests.Features.StaticData.Currencies;

/// <summary>
/// Generated DTO for entity CurrencyData.
/// </summary>
public partial record CurrencyDto
{
    /// <summary>
    /// Gets or sets the Code.
    /// </summary>
    [MaxLength(10)]
    public required string Code { get; init; }
    /// <summary>
    /// Gets or sets the Description.
    /// </summary>
    [MaxLength(200)]
    public string? Description { get; init; }
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    public int Id { get; init; }
    /// <summary>
    /// Gets or sets the IsCrypto.
    /// </summary>
    public bool IsCrypto { get; init; }
    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    [MaxLength(50)]
    public required string Name { get; init; }
}
