// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity CurrencyData.
/// </summary>
public partial record CurrencyDataDto
{
    public int Id { get; init; }
    public required string Code { get; init; }
    public string? Description { get; init; }
}
