// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests.Features.StaticData.Currencies;

/// <summary>
/// Generated DTO for entity CurrencyData.
/// </summary>
public partial record CurrencyDto
{
    public bool IsCrypto { get; init; }
    public required string Code { get; init; }
    public required string Name { get; init; }
    public string? Description { get; init; }
    public int Id { get; init; }
}
