// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity CurrencyData.
/// </summary>
public partial record CurrencyDataDto
{
    /// <summary>Gets the value mapped from entity property Id.</summary>
    public int Id { get; init; }
    /// <summary>Gets the value mapped from entity property Code.</summary>
    public required string Code { get; init; }
    /// <summary>Gets the value mapped from entity property Description.</summary>
    public string? Description { get; init; }
}
