// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests.Features.StaticData.Currencies;

/// <summary>
/// Generated DTO for entity CurrencyData.
/// </summary>
public partial record CurrencyDto
{
}
