// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
using DKNet.EfCore.DtoEntities;
using System.Collections.Generic;

namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity Customer.
/// </summary>
public partial record CustomerDto
{
    public int CustomerId { get; init; }
    public required string Name { get; init; }
    public string? Email { get; init; }
    public Address? PrimaryAddress { get; init; }
    public List<Order> Orders { get; init; } = [];
}
