// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
using DKNet.EfCore.DtoEntities;
using System.Collections.Generic;

namespace DKNet.EfCore.DtoGenerator.Tests.Features;

/// <summary>
/// Generated DTO for entity Customer.
/// </summary>
public partial record CustomerWithIncludeDto
{
    /// <summary>
    /// Gets or sets the CustomerId.
    /// </summary>
    public int CustomerId { get; init; }
    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    public required string Name { get; init; }
    /// <summary>
    /// Gets or sets the Orders.
    /// </summary>
    public ICollection<Order> Orders { get; init; } = [];
}
