// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
using Some.Others.Namespaces;
using System.Collections.Generic;

namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity Customer.
/// </summary>
public partial record CustomerDto
{
    /// <summary>Gets the value mapped from entity property CustomerId.</summary>
    public int CustomerId { get; init; }
    /// <summary>Gets the value mapped from entity property Name.</summary>
    public required string Name { get; init; }
    /// <summary>Gets the value mapped from entity property Email.</summary>
    public string? Email { get; init; }
    /// <summary>Gets the value mapped from entity property PrimaryAddress.</summary>
    public Address? PrimaryAddress { get; init; }
    /// <summary>Gets the value mapped from entity property Orders.</summary>
    public List<Order> Orders { get; init; } = [];
}
