// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity Customer.
/// </summary>
public partial record CustomerDto
{
    /// <summary>Gets the value mapped from entity property CustomerId.</summary>
    public int CustomerId { get; init; }
    /// <summary>Gets the value mapped from entity property Email.</summary>
    public string? Email { get; init; }
    /// <summary>Gets the value mapped from entity property Name.</summary>
    public required string Name { get; init; }
    /// <summary>Gets the value mapped from entity property Orders.</summary>
    public global::System.Collections.Generic.List<global::DKNet.EfCore.DtoGenerator.Tests.Order> Orders { get; init; } = [];
    /// <summary>Gets the value mapped from entity property PrimaryAddress.</summary>
    public global::DKNet.EfCore.DtoGenerator.Tests.Address? PrimaryAddress { get; init; }
}
