// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests.Features;

/// <summary>
/// Generated DTO for entity GlobalExclusionTestEntity.
/// </summary>
public partial record GlobalExclusionTestDto
{
    /// <summary>
    /// Gets or sets the Description.
    /// </summary>
    public required string Description { get; init; }
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    public Guid Id { get; init; }
    /// <summary>
    /// Gets or sets the IsActive.
    /// </summary>
    public bool IsActive { get; init; }
    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    public required string Name { get; init; }
}
