// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
using DKNet.EfCore.DtoEntities.Share;
using System.ComponentModel.DataAnnotations;

namespace DKNet.EfCore.DtoGenerator.Tests.Features.Merchants;

/// <summary>
/// Generated DTO for entity MerchantChannel.
/// </summary>
public partial record MerchantChannelDto
{
    /// <summary>
    /// Gets or sets the MerchantId.
    /// </summary>
    public Guid MerchantId { get; init; }
    /// <summary>
    /// Gets or sets the Code.
    /// </summary>
    [MaxLength(10)]
    public ChannelCodes Code { get; init; }
    /// <summary>
    /// Gets or sets the MaxAmount.
    /// </summary>
    public decimal? MaxAmount { get; init; }
    /// <summary>
    /// Gets or sets the MinAmount.
    /// </summary>
    public decimal MinAmount { get; init; }
    /// <summary>
    /// Gets or sets the Settlement.
    /// </summary>
    public required string Settlement { get; init; }
    /// <summary>
    /// Gets or sets the LastModifiedBy.
    /// </summary>
    public required string LastModifiedBy { get; init; }
    /// <summary>
    /// Gets or sets the LastModifiedOn.
    /// </summary>
    public DateTimeOffset LastModifiedOn { get; init; }
    /// <summary>
    /// Gets or sets the CreatedBy.
    /// </summary>
    [MaxLength(500)]
    public required string CreatedBy { get; init; }
    /// <summary>
    /// Gets or sets the CreatedOn.
    /// </summary>
    public DateTimeOffset CreatedOn { get; init; }
    /// <summary>
    /// Gets or sets the UpdatedBy.
    /// </summary>
    [MaxLength(500)]
    public string? UpdatedBy { get; init; }
    /// <summary>
    /// Gets or sets the UpdatedOn.
    /// </summary>
    public DateTimeOffset? UpdatedOn { get; init; }
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    public int Id { get; init; }
}
