// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
using DKNet.EfCore.DtoEntities.Features.Merchants;
using System.ComponentModel.DataAnnotations;

namespace DKNet.EfCore.DtoGenerator.Tests.Features.Merchants;

/// <summary>
/// Generated DTO for entity MerchantBalance.
/// </summary>
public partial record MerchantBalanceDto
{
    /// <summary>
    /// Gets or sets the AvailableAmount.
    /// </summary>
    public decimal AvailableAmount { get; init; }
    /// <summary>
    /// Gets or sets the AvailableCount.
    /// </summary>
    public int AvailableCount { get; init; }
    /// <summary>
    /// Gets or sets the Currency.
    /// </summary>
    [MaxLength(3)]
    public required string Currency { get; init; }
    /// <summary>
    /// Gets or sets the FeeAmount.
    /// </summary>
    public decimal FeeAmount { get; init; }
    /// <summary>
    /// Gets or sets the Merchant.
    /// </summary>
    public Merchant Merchant { get; init; } = null!;
    /// <summary>
    /// Gets or sets the MerchantId.
    /// </summary>
    public Guid MerchantId { get; init; }
    /// <summary>
    /// Gets or sets the PendingAmount.
    /// </summary>
    public decimal PendingAmount { get; init; }
    /// <summary>
    /// Gets or sets the PendingCount.
    /// </summary>
    public int PendingCount { get; init; }
    /// <summary>
    /// Gets or sets the ReservedAmount.
    /// </summary>
    public decimal ReservedAmount { get; init; }
    /// <summary>
    /// Gets or sets the RowVersion.
    /// </summary>
    public byte[]? RowVersion { get; init; }
    /// <summary>
    /// Gets or sets the CreatedOn.
    /// </summary>
    public DateTimeOffset CreatedOn { get; init; }
    /// <summary>
    /// Gets or sets the LastModifiedBy.
    /// </summary>
    public required string LastModifiedBy { get; init; }
    /// <summary>
    /// Gets or sets the LastModifiedOn.
    /// </summary>
    public DateTimeOffset LastModifiedOn { get; init; }
    /// <summary>
    /// Gets or sets the UpdatedOn.
    /// </summary>
    public DateTimeOffset? UpdatedOn { get; init; }
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    public Guid Id { get; init; }
}
