// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
using DKNet.EfCore.DtoEntities.Share;

namespace DKNet.EfCore.DtoGenerator.Tests.Features.Merchants;

/// <summary>
/// Generated DTO for entity MerchantChannel.
/// </summary>
public partial record MerchantChannelDto
{
}
