// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
using DKNet.EfCore.DtoEntities;
using System.Collections.Generic;

namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity Order.
/// </summary>
public partial record OrderDto
{
    public Guid Id { get; init; }
    public DateTime OrderedUtc { get; init; }
    public decimal Total { get; init; }
    public List<OrderItem> Items { get; init; } = [];
    public DateTime CreatedUtc { get; init; }
    public DateTime? UpdatedUtc { get; init; }
    public required string CreatedBy { get; init; }
    public string? UpdatedBy { get; init; }
}
