// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity Order.
/// </summary>
public partial record OrderSummaryDto
{
    /// <summary>Gets the value mapped from entity property Items.</summary>
    public global::System.Collections.Generic.List<global::DKNet.EfCore.DtoGenerator.Tests.OrderItem> Items { get; init; } = [];
    /// <summary>Gets the value mapped from entity property Total.</summary>
    public decimal Total { get; init; }
}
