// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity OrderItem.
/// </summary>
public partial record OrderItemDto
{
    public int Id { get; init; }
    public required string Sku { get; init; }
    public int Quantity { get; init; }
    public decimal Price { get; init; }
}
