// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
using Some.Others.Namespaces;
using System.Collections.Generic;

namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity Order.
/// </summary>
public partial record OrderSummaryDto
{
    /// <summary>Gets the value mapped from entity property Total.</summary>
    public decimal Total { get; init; }
    /// <summary>Gets the value mapped from entity property Items.</summary>
    public List<OrderItem> Items { get; init; } = [];
}
