// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity OrderItem.
/// </summary>
public partial record OrderItemDto
{
    /// <summary>Gets the value mapped from entity property Id.</summary>
    public int Id { get; init; }
    /// <summary>Gets the value mapped from entity property Sku.</summary>
    public required string Sku { get; init; }
    /// <summary>Gets the value mapped from entity property Quantity.</summary>
    public int Quantity { get; init; }
    /// <summary>Gets the value mapped from entity property Price.</summary>
    public decimal Price { get; init; }
}
