// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity Person.
/// </summary>
public partial record PersonCustomDto
{
    /// <summary>Gets the value mapped from entity property Id.</summary>
    public Guid Id { get; init; }
    /// <summary>Gets the value mapped from entity property MiddleName.</summary>
    public string? MiddleName { get; init; }
    /// <summary>Gets the value mapped from entity property LastName.</summary>
    public required string LastName { get; init; }
    /// <summary>Gets the value mapped from entity property CreatedUtc.</summary>
    public DateTime CreatedUtc { get; init; }
    /// <summary>Gets the value mapped from entity property Age.</summary>
    public int Age { get; init; }
}
