// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests.Features;

/// <summary>
/// Generated DTO for entity Person.
/// </summary>
public partial record PersonNameDto
{
    public required string FirstName { get; init; }
    public required string LastName { get; init; }
}
