// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity Person.
/// </summary>
public partial record PersonBasicDto
{
    /// <summary>Gets the value mapped from entity property FirstName.</summary>
    public required string FirstName { get; init; }
    /// <summary>Gets the value mapped from entity property Id.</summary>
    public global::System.Guid Id { get; init; }
    /// <summary>Gets the value mapped from entity property LastName.</summary>
    public required string LastName { get; init; }
}
