// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity Person.
/// </summary>
public partial record PersonCustomDto
{
    public Guid Id { get; init; }
    public string? MiddleName { get; init; }
    public required string LastName { get; init; }
    public DateTime CreatedUtc { get; init; }
    public int Age { get; init; }
}
