// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests.Features;

/// <summary>
/// Generated DTO for entity Person.
/// </summary>
public partial record PersonSummaryDto
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    public Guid Id { get; init; }
    /// <summary>
    /// Gets or sets the FirstName.
    /// </summary>
    public required string FirstName { get; init; }
    /// <summary>
    /// Gets or sets the LastName.
    /// </summary>
    public required string LastName { get; init; }
    /// <summary>
    /// Gets or sets the Age.
    /// </summary>
    public int Age { get; init; }
}
