// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity Person.
/// </summary>
public partial record PersonBasicDto
{
    public Guid Id { get; init; }
    public required string FirstName { get; init; }
    public required string LastName { get; init; }
    public DateTime? UpdatedUtc { get; init; }
    public required string CreatedBy { get; init; }
    public string? UpdatedBy { get; init; }
}
