// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
namespace DKNet.EfCore.DtoGenerator.Tests;

/// <summary>
/// Generated DTO for entity Person.
/// </summary>
public partial record PersonCustomDto
{
}
