// <auto-generated/> Generated by DKNet.EfCore.DtoGenerator
#nullable enable
using System.ComponentModel.DataAnnotations;

namespace DKNet.EfCore.DtoGenerator.Tests.Features;

/// <summary>
/// Generated DTO for entity TestProduct.
/// </summary>
public partial record TestProductDto
{
    /// <summary>
    /// Gets or sets the CreatedDate.
    /// </summary>
    public DateTime CreatedDate { get; init; }
    /// <summary>
    /// Gets or sets the Description.
    /// </summary>
    [MaxLength(500)]
    public string? Description { get; init; }
    /// <summary>
    /// Gets or sets the Email.
    /// </summary>
    [EmailAddress]
    [MaxLength(200)]
    public required string Email { get; init; }
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    public Guid Id { get; init; }
    /// <summary>
    /// Gets or sets the IsActive.
    /// </summary>
    public bool IsActive { get; init; }
    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    [Required]
    [StringLength(100, MinimumLength = 3)]
    public required string Name { get; init; }
    /// <summary>
    /// Gets or sets the PhoneNumber.
    /// </summary>
    [Phone]
    public string? PhoneNumber { get; init; }
    /// <summary>
    /// Gets or sets the Price.
    /// </summary>
    [Range(0.01, 999999.99)]
    public decimal Price { get; init; }
    /// <summary>
    /// Gets or sets the Sku.
    /// </summary>
    [Required]
    [MaxLength(50)]
    public required string Sku { get; init; }
    /// <summary>
    /// Gets or sets the StockQuantity.
    /// </summary>
    [Range(0, 10000)]
    public int StockQuantity { get; init; }
    /// <summary>
    /// Gets or sets the WebsiteUrl.
    /// </summary>
    public Uri? WebsiteUrl { get; init; }
}
