name: Build and Collect Warnings

on:
  push:
    branches: ["dev"]

jobs:
  build-and-collect-warnings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release 2>&1 | tee build.log

      - name: Extract warnings
        run: grep -i "Warning" build.log > warnings.log || true

      - name: Create issue with warnings
        if: always()
        uses: peter-evans/create-issue-from-file@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Build Warnings"
          content-file: "warnings.log"
          labels: |
            build
            warnings